FROM rust:slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    make \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Pre-fetch dependencies
RUN cargo fetch

CMD ["make", "test"]
