//! Agent session schema elements for the project schema.

use super::ForeignKeyDef;
use crate::constants::keys;
use crate::schema::memory::{ColumnDef, ColumnType, IndexDef, TableDef};

pub fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "agent_sessions".to_string(),
            columns: vec![
                ColumnDef {
                    name: keys::ID.to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::SESSION_SUMMARY_ID.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::AGENT_TYPE.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::MODEL.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::PARENT_SESSION_ID.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::STARTED_AT.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::ENDED_AT.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::DURATION_MS.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::STATUS.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::PROMPT_SUMMARY.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::RESULT_SUMMARY.to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::TOKEN_COUNT.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::TOOL_CALLS_COUNT.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: keys::DELEGATIONS_COUNT.to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "delegations".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "parent_session_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "child_session_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "prompt".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "prompt_embedding_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "result".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "success".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "completed_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "duration_ms".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "tool_calls".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "session_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "tool_name".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "params_summary".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "success".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "error_message".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "duration_ms".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "checkpoints".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "session_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "checkpoint_type".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "description".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "snapshot_data".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "restored_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "expired".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
            ],
        },
    ]
}

pub fn indexes() -> Vec<IndexDef> {
    vec![
        IndexDef {
            name: "idx_agent_sessions_parent".to_string(),
            table: "agent_sessions".to_string(),
            columns: vec!["parent_session_id".to_string()],
        },
        IndexDef {
            name: "idx_agent_sessions_type".to_string(),
            table: "agent_sessions".to_string(),
            columns: vec!["agent_type".to_string()],
        },
        IndexDef {
            name: "idx_agent_sessions_started".to_string(),
            table: "agent_sessions".to_string(),
            columns: vec!["started_at".to_string()],
        },
        IndexDef {
            name: "idx_delegations_parent".to_string(),
            table: "delegations".to_string(),
            columns: vec!["parent_session_id".to_string()],
        },
        IndexDef {
            name: "idx_delegations_child".to_string(),
            table: "delegations".to_string(),
            columns: vec!["child_session_id".to_string()],
        },
        IndexDef {
            name: "idx_tool_calls_session".to_string(),
            table: "tool_calls".to_string(),
            columns: vec!["session_id".to_string()],
        },
        IndexDef {
            name: "idx_tool_calls_tool".to_string(),
            table: "tool_calls".to_string(),
            columns: vec!["tool_name".to_string()],
        },
        IndexDef {
            name: "idx_checkpoints_session".to_string(),
            table: "checkpoints".to_string(),
            columns: vec!["session_id".to_string()],
        },
    ]
}

pub fn foreign_keys() -> Vec<ForeignKeyDef> {
    vec![
        ForeignKeyDef {
            from_table: "agent_sessions".to_string(),
            from_column: "session_summary_id".to_string(),
            to_table: "session_summaries".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "agent_sessions".to_string(),
            from_column: "parent_session_id".to_string(),
            to_table: "agent_sessions".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "delegations".to_string(),
            from_column: "parent_session_id".to_string(),
            to_table: "agent_sessions".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "delegations".to_string(),
            from_column: "child_session_id".to_string(),
            to_table: "agent_sessions".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "tool_calls".to_string(),
            from_column: "session_id".to_string(),
            to_table: "agent_sessions".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "checkpoints".to_string(),
            from_column: "session_id".to_string(),
            to_table: "agent_sessions".to_string(),
            to_column: "id".to_string(),
        },
    ]
}
