//! Workflow schema elements for project phases, issues, dependencies, and decisions.

use super::ForeignKeyDef;
use crate::schema::memory::{ColumnDef, ColumnType, IndexDef, TableDef};

pub fn tables() -> Vec<TableDef> {
    vec![
        TableDef {
            name: "project_phases".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "project_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "name".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "description".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "sequence".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "status".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "started_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "completed_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "updated_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "project_issues".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "project_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "phase_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "title".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "description".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "issue_type".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "status".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "priority".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "assignee".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "labels".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "updated_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "closed_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "project_dependencies".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "from_issue_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "to_issue_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "dependency_type".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
            ],
        },
        TableDef {
            name: "project_decisions".to_string(),
            columns: vec![
                ColumnDef {
                    name: "id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: true,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "project_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "issue_id".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: false,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "title".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "context".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "decision".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "consequences".to_string(),
                    type_: ColumnType::Text,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
                ColumnDef {
                    name: "created_at".to_string(),
                    type_: ColumnType::Integer,
                    primary_key: false,
                    unique: false,
                    not_null: true,
                    auto_increment: false,
                },
            ],
        },
    ]
}

pub fn indexes() -> Vec<IndexDef> {
    vec![
        IndexDef {
            name: "idx_project_phases_project".to_string(),
            table: "project_phases".to_string(),
            columns: vec!["project_id".to_string()],
        },
        IndexDef {
            name: "idx_project_phases_status".to_string(),
            table: "project_phases".to_string(),
            columns: vec!["status".to_string()],
        },
        IndexDef {
            name: "idx_project_issues_project".to_string(),
            table: "project_issues".to_string(),
            columns: vec!["project_id".to_string()],
        },
        IndexDef {
            name: "idx_project_issues_phase".to_string(),
            table: "project_issues".to_string(),
            columns: vec!["phase_id".to_string()],
        },
        IndexDef {
            name: "idx_project_issues_status".to_string(),
            table: "project_issues".to_string(),
            columns: vec!["status".to_string()],
        },
        IndexDef {
            name: "idx_project_issues_priority".to_string(),
            table: "project_issues".to_string(),
            columns: vec!["priority".to_string()],
        },
        IndexDef {
            name: "idx_project_dependencies_from".to_string(),
            table: "project_dependencies".to_string(),
            columns: vec!["from_issue_id".to_string()],
        },
        IndexDef {
            name: "idx_project_dependencies_to".to_string(),
            table: "project_dependencies".to_string(),
            columns: vec!["to_issue_id".to_string()],
        },
        IndexDef {
            name: "idx_project_decisions_project".to_string(),
            table: "project_decisions".to_string(),
            columns: vec!["project_id".to_string()],
        },
        IndexDef {
            name: "idx_project_decisions_issue".to_string(),
            table: "project_decisions".to_string(),
            columns: vec!["issue_id".to_string()],
        },
    ]
}

pub fn foreign_keys() -> Vec<ForeignKeyDef> {
    vec![
        ForeignKeyDef {
            from_table: "project_phases".to_string(),
            from_column: "project_id".to_string(),
            to_table: "projects".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_issues".to_string(),
            from_column: "project_id".to_string(),
            to_table: "projects".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_issues".to_string(),
            from_column: "phase_id".to_string(),
            to_table: "project_phases".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_dependencies".to_string(),
            from_column: "from_issue_id".to_string(),
            to_table: "project_issues".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_dependencies".to_string(),
            from_column: "to_issue_id".to_string(),
            to_table: "project_issues".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_decisions".to_string(),
            from_column: "project_id".to_string(),
            to_table: "projects".to_string(),
            to_column: "id".to_string(),
        },
        ForeignKeyDef {
            from_table: "project_decisions".to_string(),
            from_column: "issue_id".to_string(),
            to_table: "project_issues".to_string(),
            to_column: "id".to_string(),
        },
    ]
}
