"""Synchronize generated agent pointer files.

Copyright (c) 2025 MCB Contributors. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path
from typing import NamedTuple

from flext_core import FlextResult, p
from pydantic import BaseModel

from flext_cli import cli
from mcb_scripts.logger import get_logger

logger = get_logger(__name__)

GENERATED = "<!-- generated by `make gen-agent-pointers`; source: AGENTS.md -->"


class SyncResult(NamedTuple):
    """Outcome of one agent-pointer synchronization run."""

    changed_paths: list[str]


class AgentPointerParams(BaseModel):
    """Command parameters for the agent-pointer verb."""

    check: bool = False
    root: Path = Path.cwd()


# `from __future__ import annotations` defers every annotation to a string, and
# the CLI facade resolves the model in ITS namespace, where names like Path are
# absent. Rebuilding here binds them in the module that actually declares them.
AgentPointerParams.model_rebuild()


def _pointer(title: str, agents_path: str) -> str:
    return (
        f"{GENERATED}\n"
        f"# {title}\n\n"
        f"`{agents_path}` is the project single source of truth for all agent rules,\n"
        "architecture, commands, beads workflow, validation, and Git policy.\n\n"
        "Do not duplicate those rules here. Update `AGENTS.md`, then run\n"
        "`make gen-agent-pointers`.\n"
    )


def _frontmatter_pointer(title: str, agents_path: str, frontmatter: str) -> str:
    return f"{frontmatter}\n{_pointer(title, agents_path)}"


def render_all() -> dict[str, str]:
    """Render every agent pointer file keyed by its repository path."""
    return {
        "CLAUDE.md": (
            f"{GENERATED}\n"
            "# CLAUDE.md — MCB Project Instructions\n\n"
            "Reference [`./AGENTS.md`](./AGENTS.md) for all project rules,\n"
            "architecture, commands, beads workflow, validation, and Git policy.\n"
            "Do not duplicate those rules here.\n\n"
            "<!-- bd-doctor-divergence: ok -->\n"
            "<!-- Intentional: this file is a generated thin pointer to AGENTS.md. -->\n"
        ),
        "GEMINI.md": _pointer("GEMINI.md — MCB Project Instructions", "./AGENTS.md"),
        ".clinerules": _pointer("MCB — Cline Rules", "AGENTS.md"),
        ".windsurfrules": _pointer("MCB — Windsurf Rules", "AGENTS.md"),
        "CONVENTIONS.md": _pointer("MCB — Conventions (Aider)", "AGENTS.md"),
        "codex.md": _pointer("Codex Instructions — MCB", "AGENTS.md"),
        ".github/copilot-instructions.md": _pointer(
            "Copilot Instructions — MCB", "../AGENTS.md"
        ),
        ".continue/rules/mcb.md": _frontmatter_pointer(
            "MCB — Continue.dev Rules",
            "../../AGENTS.md",
            '---\nname: MCB Project Rules\nglobs: ["**/*.rs", "**/*.toml", "**/*.md"]\n---',
        ),
        ".cursor/rules/mcb.mdc": _frontmatter_pointer(
            "MCB — Cursor AI Rules",
            "../../AGENTS.md",
            (
                "---\n"
                "description: MCB project rules for Cursor AI\n"
                'globs: ["**/*.rs", "**/*.toml", "**/*.md"]\n'
                "alwaysApply: true\n"
                "---"
            ),
        ),
        ".gemini/styleguide.md": (
            f"{GENERATED}\n"
            "# MCB — Gemini Code Assist Style Guide\n\n"
            "Single source of truth: [`AGENTS.md`](../AGENTS.md). This file only\n"
            "adds Gemini-specific review ordering and must not restate project rules.\n\n"
            "## PR Review Priorities\n\n"
            "1. Architecture boundaries\n"
            "2. Safety\n"
            "3. Correctness\n"
            "4. Performance\n"
            "5. Maintainability\n"
            "6. Security\n"
            "7. Tests\n"
        ),
    }


def sync(root: Path, *, check: bool) -> SyncResult:
    """Write the rendered pointers under root, reporting what changed."""
    agents = root / "AGENTS.md"
    if not agents.is_file():
        msg = f"missing SSOT: {agents}"
        raise FileNotFoundError(msg)

    changed_paths: list[str] = []
    for relative_path, expected in render_all().items():
        path = root / relative_path
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        changed_paths.append(relative_path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    return SyncResult(changed_paths)


def generate(params: AgentPointerParams) -> p.Result[SyncResult]:
    """Generate or check agent pointer files."""
    result = sync(params.root.resolve(), check=params.check)
    if result.changed_paths:
        action = "out of sync" if params.check else "updated"
        for path in result.changed_paths:
            logger.info(f"{action}: {path}")
        if params.check:
            return FlextResult[SyncResult].fail("agent pointers are out of sync")
        return FlextResult[SyncResult].ok(result)

    logger.info("agent pointers in sync")
    return FlextResult[SyncResult].ok(result)


def main() -> None:
    """Entry point for the agent-pointer generation command."""
    app = cli.create_app_with_common_params(
        name="agent-pointers", help_text="Synchronize generated agent pointer files."
    )
    cli.register_result_command(
        app,
        name="generate",
        help_text="Generate or check agent pointer files.",
        model_cls=AgentPointerParams,
        handler=generate,
    )
    result = cli.execute_app(app, prog_name="agent-pointers")
    if result.failure:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
