#!/usr/bin/env bash
# Generated by flext-infra. AI Hub owns Git hook installation.
set -euo pipefail
stage="${1:?Git hook stage is required}"
cd "$(git rev-parse --show-toplevel)"
case "$stage" in
  pre-commit|pre-merge-commit)
    if ! git diff --quiet --ignore-submodules=none || [ -n "$(git ls-files --others --exclude-standard)" ]; then
      printf '%s\n' 'Commit blocked: stage the complete candidate before validation; partial staging is preserved.' >&2
      exit 1
    fi
    ;;
  pre-push)
    test -z "$(git status --porcelain --untracked-files=all --ignore-submodules=none)"
    ;;
  *) printf 'Unsupported Git hook stage: %s\n' "$stage" >&2; exit 2 ;;
esac
# --all-files avoids pre-commit hook-impl's stash of unstaged changes.
unset SKIP PRE_COMMIT_ALLOW_NO_CONFIG
pre-commit run --all-files --hook-stage "$stage"
