"""Lib Tests Test Agent Pointers.

Copyright (c) 2025 MCB Contributors. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

from ._utilities.matchers import tm

ROOT = Path(__file__).resolve().parents[3]
MODULE_PATH = ROOT / "scripts" / "lib" / "agent_pointers.py"
SPEC = importlib.util.spec_from_file_location("mcb_agent_pointers", MODULE_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"failed to load module spec for {MODULE_PATH}")
agent_pointers = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(agent_pointers)


def test_all_rendered_pointers_reference_agents_ssot() -> None:
    for path, content in agent_pointers.render_all().items():
        assert "AGENTS.md" in content, f"{path}: missing AGENTS.md reference"
        assert "generated by `make gen-agent-pointers`" in content, (
            f"{path}: missing generator marker"
        )
        assert "Architecture Violation Codes" not in content, (
            f"{path}: contains forbidden section"
        )
        assert "Forbidden Patterns" not in content, (
            f"{path}: contains forbidden section"
        )
        assert "Quick Reference" not in content, f"{path}: contains forbidden section"


def test_rendered_pointer_files_are_not_ignored() -> None:
    ignored = {
        line.strip()
        for line in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    for path in agent_pointers.render_all():
        tm.that(path not in ignored, f"{path} is ignored")


def test_check_detects_drift_without_writing(temp_dir: Path) -> None:
    (temp_dir / "AGENTS.md").write_text("# AGENTS\n", encoding="utf-8")
    first_path = next(iter(agent_pointers.render_all()))
    pointer_path = temp_dir / first_path
    pointer_path.parent.mkdir(parents=True, exist_ok=True)
    pointer_path.write_text("stale\n", encoding="utf-8")

    result = agent_pointers.sync(temp_dir, check=True)

    assert [first_path] == result.changed_paths[:1]
    assert pointer_path.read_text(encoding="utf-8") == "stale\n"


def test_sync_writes_all_pointer_files(temp_dir: Path) -> None:
    (temp_dir / "AGENTS.md").write_text("# AGENTS\n", encoding="utf-8")

    result = agent_pointers.sync(temp_dir, check=False)

    assert set(agent_pointers.render_all()) == set(result.changed_paths)
    for path, expected in agent_pointers.render_all().items():
        assert expected == (temp_dir / path).read_text(encoding="utf-8")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
