//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::agent_worktree_assignment;
use mcb_domain::entities::AgentWorktreeAssignment;

impl From<agent_worktree_assignment::Model> for AgentWorktreeAssignment {
    fn from(m: agent_worktree_assignment::Model) -> Self {
        Self {
            id: m.id,
            agent_session_id: m.agent_session_id,
            worktree_id: m.worktree_id,
            assigned_at: m.assigned_at,
            released_at: m.released_at,
        }
    }
}

impl From<AgentWorktreeAssignment> for agent_worktree_assignment::ActiveModel {
    fn from(e: AgentWorktreeAssignment) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            agent_session_id: ActiveValue::Set(e.agent_session_id),
            worktree_id: ActiveValue::Set(e.worktree_id),
            assigned_at: ActiveValue::Set(e.assigned_at),
            released_at: ActiveValue::Set(e.released_at),
            origin_context: ActiveValue::NotSet,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_agent_worktree_assignment() -> agent_worktree_assignment::Model {
        agent_worktree_assignment::Model {
            id: "agent_worktree_assignment_test_001".into(),
            agent_session_id: "ref_agent_session_id_001".into(),
            worktree_id: "ref_worktree_id_001".into(),
            assigned_at: 1_700_000_000,
            released_at: Some(1_700_000_000),
            origin_context: None,
        }
    }

    #[test]
    fn round_trip_agent_worktree_assignment() {
        let model = sample_agent_worktree_assignment();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: AgentWorktreeAssignment = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: agent_worktree_assignment::ActiveModel = domain.into();
    }
}
