//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::agent_session;
use mcb_domain::entities::AgentSession;
use mcb_domain::entities::agent::{AgentSessionStatus, AgentType};

impl From<agent_session::Model> for AgentSession {
    fn from(m: agent_session::Model) -> Self {
        Self {
            id: m.id,
            session_summary_id: m.session_summary_id,
            model: m.model,
            parent_session_id: m.parent_session_id,
            started_at: m.started_at,
            ended_at: m.ended_at,
            duration_ms: m.duration_ms,
            prompt_summary: m.prompt_summary,
            result_summary: m.result_summary,
            token_count: m.token_count,
            tool_calls_count: m.tool_calls_count,
            delegations_count: m.delegations_count,
            project_id: m.project_id,
            worktree_id: m.worktree_id,
            agent_type: m.agent_type.parse::<AgentType>().unwrap_or(AgentType::Sisyphus),
            status: m.status.parse::<AgentSessionStatus>().unwrap_or(AgentSessionStatus::Active),
        }
    }
}

impl From<AgentSession> for agent_session::ActiveModel {
    fn from(e: AgentSession) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            session_summary_id: ActiveValue::Set(e.session_summary_id),
            model: ActiveValue::Set(e.model),
            parent_session_id: ActiveValue::Set(e.parent_session_id),
            started_at: ActiveValue::Set(e.started_at),
            ended_at: ActiveValue::Set(e.ended_at),
            duration_ms: ActiveValue::Set(e.duration_ms),
            prompt_summary: ActiveValue::Set(e.prompt_summary),
            result_summary: ActiveValue::Set(e.result_summary),
            token_count: ActiveValue::Set(e.token_count),
            tool_calls_count: ActiveValue::Set(e.tool_calls_count),
            delegations_count: ActiveValue::Set(e.delegations_count),
            project_id: ActiveValue::Set(e.project_id),
            worktree_id: ActiveValue::Set(e.worktree_id),
            agent_type: ActiveValue::Set(e.agent_type.to_string()),
            status: ActiveValue::Set(e.status.to_string()),
        }
    }
}
