//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::api_key;
use mcb_domain::entities::ApiKey;

impl From<api_key::Model> for ApiKey {
    fn from(m: api_key::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            user_id: m.user_id,
            key_hash: m.key_hash,
            name: m.name,
            scopes_json: m.scopes_json,
            expires_at: m.expires_at,
            created_at: m.created_at,
            revoked_at: m.revoked_at,
        }
    }
}

impl From<ApiKey> for api_key::ActiveModel {
    fn from(e: ApiKey) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            user_id: ActiveValue::Set(e.user_id),
            key_hash: ActiveValue::Set(e.key_hash),
            name: ActiveValue::Set(e.name),
            scopes_json: ActiveValue::Set(e.scopes_json),
            expires_at: ActiveValue::Set(e.expires_at),
            created_at: ActiveValue::Set(e.created_at),
            revoked_at: ActiveValue::Set(e.revoked_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_api_key() -> api_key::Model {
        api_key::Model {
            id: "api_key_test_001".into(),
            user_id: "ref_user_id_001".into(),
            org_id: "ref_org_id_001".into(),
            key_hash: "hash_api_key_001".into(),
            name: "test_name".into(),
            scopes_json: "{}".into(),
            expires_at: Some(1_700_000_000),
            created_at: 1_700_000_000,
            revoked_at: Some(1_700_000_000),
        }
    }

    #[test]
    fn round_trip_api_key() {
        let model = sample_api_key();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: ApiKey = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: api_key::ActiveModel = domain.into();
    }
}
