//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::branch;
use mcb_domain::entities::Branch;

impl From<branch::Model> for Branch {
    fn from(m: branch::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            repository_id: m.repository_id,
            name: m.name,
            head_commit: m.head_commit,
            upstream: m.upstream,
            created_at: m.created_at,
            is_default: m.is_default != 0,
        }
    }
}

impl From<Branch> for branch::ActiveModel {
    fn from(e: Branch) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            repository_id: ActiveValue::Set(e.repository_id),
            name: ActiveValue::Set(e.name),
            head_commit: ActiveValue::Set(e.head_commit),
            upstream: ActiveValue::Set(e.upstream),
            created_at: ActiveValue::Set(e.created_at),
            is_default: ActiveValue::Set(i64::from(e.is_default)),
            project_id: ActiveValue::NotSet,
            origin_context: ActiveValue::NotSet,
        }
    }
}
