//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::branch;
use mcb_domain::entities::Branch;

impl From<branch::Model> for Branch {
    fn from(m: branch::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            repository_id: m.repository_id,
            name: m.name,
            head_commit: m.head_commit,
            upstream: m.upstream,
            created_at: m.created_at,
            is_default: m.is_default != 0,
        }
    }
}

impl From<Branch> for branch::ActiveModel {
    fn from(e: Branch) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            repository_id: ActiveValue::Set(e.repository_id),
            name: ActiveValue::Set(e.name),
            head_commit: ActiveValue::Set(e.head_commit),
            upstream: ActiveValue::Set(e.upstream),
            created_at: ActiveValue::Set(e.created_at),
            is_default: ActiveValue::Set(i64::from(e.is_default)),
            project_id: ActiveValue::NotSet,
            origin_context: ActiveValue::NotSet,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_branch() -> branch::Model {
        branch::Model {
            id: "branch_test_001".into(),
            org_id: "ref_org_id_001".into(),
            project_id: None,
            repository_id: "ref_repository_id_001".into(),
            name: "test_name".into(),
            is_default: 1,
            head_commit: "test_head_commit".into(),
            upstream: Some("test_upstream".into()),
            origin_context: None,
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_branch() {
        let model = sample_branch();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Branch = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: branch::ActiveModel = domain.into();
    }
}
