//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::checkpoint;
use mcb_domain::entities::Checkpoint;
use mcb_domain::entities::agent::CheckpointType;

impl From<checkpoint::Model> for Checkpoint {
    fn from(m: checkpoint::Model) -> Self {
        Self {
            id: m.id,
            session_id: m.session_id,
            description: m.description,
            created_at: m.created_at,
            restored_at: m.restored_at,
            checkpoint_type: m.checkpoint_type.parse::<CheckpointType>().unwrap_or(CheckpointType::File),
            snapshot_data: serde_json::from_str(&m.snapshot_data).unwrap_or(serde_json::Value::Null),
            expired: m.expired.is_some_and(|v| v != 0),
        }
    }
}

impl From<Checkpoint> for checkpoint::ActiveModel {
    fn from(e: Checkpoint) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            session_id: ActiveValue::Set(e.session_id),
            description: ActiveValue::Set(e.description),
            created_at: ActiveValue::Set(e.created_at),
            restored_at: ActiveValue::Set(e.restored_at),
            checkpoint_type: ActiveValue::Set(e.checkpoint_type.to_string()),
            snapshot_data: ActiveValue::Set(
                serde_json::to_string(&e.snapshot_data).unwrap_or_default(),
            ),
            expired: ActiveValue::Set(Some(i64::from(e.expired))),
        }
    }
}
