//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::delegation;
use mcb_domain::entities::Delegation;

impl From<delegation::Model> for Delegation {
    fn from(m: delegation::Model) -> Self {
        Self {
            id: m.id,
            parent_session_id: m.parent_session_id,
            child_session_id: m.child_session_id,
            prompt: m.prompt,
            prompt_embedding_id: m.prompt_embedding_id,
            result: m.result,
            created_at: m.created_at,
            completed_at: m.completed_at,
            duration_ms: m.duration_ms,
            success: m.success != 0,
        }
    }
}

impl From<Delegation> for delegation::ActiveModel {
    fn from(e: Delegation) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            parent_session_id: ActiveValue::Set(e.parent_session_id),
            child_session_id: ActiveValue::Set(e.child_session_id),
            prompt: ActiveValue::Set(e.prompt),
            prompt_embedding_id: ActiveValue::Set(e.prompt_embedding_id),
            result: ActiveValue::Set(e.result),
            created_at: ActiveValue::Set(e.created_at),
            completed_at: ActiveValue::Set(e.completed_at),
            duration_ms: ActiveValue::Set(e.duration_ms),
            success: ActiveValue::Set(i64::from(e.success)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_delegation() -> delegation::Model {
        delegation::Model {
            id: "delegation_test_001".into(),
            parent_session_id: "ref_parent_session_id_001".into(),
            child_session_id: "ref_child_session_id_001".into(),
            prompt: "test_prompt".into(),
            prompt_embedding_id: Some("test_prompt_embedding_id".into()),
            result: Some("test_result".into()),
            success: 1,
            created_at: 1_700_000_000,
            completed_at: Some(1_700_000_000),
            duration_ms: Some(1500),
        }
    }

    #[test]
    fn round_trip_delegation() {
        let model = sample_delegation();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Delegation = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: delegation::ActiveModel = domain.into();
    }
}
