//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::delegation;
use mcb_domain::entities::Delegation;

impl From<delegation::Model> for Delegation {
    fn from(m: delegation::Model) -> Self {
        Self {
            id: m.id,
            parent_session_id: m.parent_session_id,
            child_session_id: m.child_session_id,
            prompt: m.prompt,
            prompt_embedding_id: m.prompt_embedding_id,
            result: m.result,
            created_at: m.created_at,
            completed_at: m.completed_at,
            duration_ms: m.duration_ms,
            success: m.success != 0,
        }
    }
}

impl From<Delegation> for delegation::ActiveModel {
    fn from(e: Delegation) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            parent_session_id: ActiveValue::Set(e.parent_session_id),
            child_session_id: ActiveValue::Set(e.child_session_id),
            prompt: ActiveValue::Set(e.prompt),
            prompt_embedding_id: ActiveValue::Set(e.prompt_embedding_id),
            result: ActiveValue::Set(e.result),
            created_at: ActiveValue::Set(e.created_at),
            completed_at: ActiveValue::Set(e.completed_at),
            duration_ms: ActiveValue::Set(e.duration_ms),
            success: ActiveValue::Set(i64::from(e.success)),
        }
    }
}
