//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::error_pattern_match;
use mcb_domain::entities::memory::ErrorPatternMatch;

impl From<error_pattern_match::Model> for ErrorPatternMatch {
    fn from(m: error_pattern_match::Model) -> Self {
        Self {
            id: m.id,
            pattern_id: m.pattern_id,
            observation_id: m.observation_id,
            confidence: m.confidence,
            matched_at: m.matched_at,
            resolved_at: m.resolved_at,
            solution_applied: m.solution_applied.map(|v| v as i32),
            resolution_successful: m.resolution_successful.map(|v| v != 0),
        }
    }
}

impl From<ErrorPatternMatch> for error_pattern_match::ActiveModel {
    fn from(e: ErrorPatternMatch) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            pattern_id: ActiveValue::Set(e.pattern_id),
            observation_id: ActiveValue::Set(e.observation_id),
            confidence: ActiveValue::Set(e.confidence),
            matched_at: ActiveValue::Set(e.matched_at),
            resolved_at: ActiveValue::Set(e.resolved_at),
            solution_applied: ActiveValue::Set(e.solution_applied.map(i64::from)),
            resolution_successful: ActiveValue::Set(e.resolution_successful.map(i64::from)),
        }
    }
}
