//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::error_pattern;
use mcb_domain::entities::memory::{ErrorPattern, ErrorPatternCategory};

impl From<error_pattern::Model> for ErrorPattern {
    fn from(m: error_pattern::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            pattern_signature: m.pattern_signature,
            description: m.description,
            occurrence_count: m.occurrence_count,
            first_seen_at: m.first_seen_at,
            last_seen_at: m.last_seen_at,
            embedding_id: m.embedding_id,
            category: m.category.parse::<ErrorPatternCategory>().unwrap_or(ErrorPatternCategory::Other),
            solutions: m
                .solutions
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
            affected_files: m
                .affected_files
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
            tags: m
                .tags
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
        }
    }
}

impl From<ErrorPattern> for error_pattern::ActiveModel {
    fn from(e: ErrorPattern) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            pattern_signature: ActiveValue::Set(e.pattern_signature),
            description: ActiveValue::Set(e.description),
            occurrence_count: ActiveValue::Set(e.occurrence_count),
            first_seen_at: ActiveValue::Set(e.first_seen_at),
            last_seen_at: ActiveValue::Set(e.last_seen_at),
            embedding_id: ActiveValue::Set(e.embedding_id),
            category: ActiveValue::Set(e.category.to_string()),
            solutions: ActiveValue::Set(Some(
                serde_json::to_string(&e.solutions).unwrap_or_else(|_| "[]".into()),
            )),
            affected_files: ActiveValue::Set(Some(
                serde_json::to_string(&e.affected_files).unwrap_or_else(|_| "[]".into()),
            )),
            tags: ActiveValue::Set(Some(
                serde_json::to_string(&e.tags).unwrap_or_else(|_| "[]".into()),
            )),
        }
    }
}
