//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_label;
use mcb_domain::entities::IssueLabel;

impl From<issue_label::Model> for IssueLabel {
    fn from(m: issue_label::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            name: m.name,
            color: m.color,
            created_at: m.created_at,
        }
    }
}

impl From<IssueLabel> for issue_label::ActiveModel {
    fn from(e: IssueLabel) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            name: ActiveValue::Set(e.name),
            color: ActiveValue::Set(e.color),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_issue_label() -> issue_label::Model {
        issue_label::Model {
            id: "issue_label_test_001".into(),
            org_id: "ref_org_id_001".into(),
            project_id: "ref_project_id_001".into(),
            name: "test_name".into(),
            color: "test_color".into(),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_issue_label() {
        let model = sample_issue_label();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: IssueLabel = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: issue_label::ActiveModel = domain.into();
    }
}
