//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_label_assignment;
use mcb_domain::entities::issue::IssueLabelAssignment;
use mcb_domain::value_objects::ids::IssueLabelAssignmentId;

impl From<issue_label_assignment::Model> for IssueLabelAssignment {
    fn from(m: issue_label_assignment::Model) -> Self {
        Self {
            id: IssueLabelAssignmentId::from(format!("{}:{}", m.issue_id, m.label_id).as_str()),
            issue_id: m.issue_id,
            label_id: m.label_id,
            created_at: m.created_at,
        }
    }
}

impl From<IssueLabelAssignment> for issue_label_assignment::ActiveModel {
    fn from(e: IssueLabelAssignment) -> Self {
        Self {
            issue_id: ActiveValue::Set(e.issue_id),
            label_id: ActiveValue::Set(e.label_id),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}
