//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_comment;
use mcb_domain::entities::IssueComment;

impl From<issue_comment::Model> for IssueComment {
    fn from(m: issue_comment::Model) -> Self {
        Self {
            id: m.id,
            issue_id: m.issue_id,
            author_id: m.author_id,
            content: m.content,
            created_at: m.created_at,
        }
    }
}

impl From<IssueComment> for issue_comment::ActiveModel {
    fn from(e: IssueComment) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            issue_id: ActiveValue::Set(e.issue_id),
            author_id: ActiveValue::Set(e.author_id),
            content: ActiveValue::Set(e.content),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}
