//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_label;
use mcb_domain::entities::IssueLabel;

impl From<issue_label::Model> for IssueLabel {
    fn from(m: issue_label::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            name: m.name,
            color: m.color,
            created_at: m.created_at,
        }
    }
}

impl From<IssueLabel> for issue_label::ActiveModel {
    fn from(e: IssueLabel) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            name: ActiveValue::Set(e.name),
            color: ActiveValue::Set(e.color),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}
