//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_label_assignment;
use mcb_domain::entities::issue::IssueLabelAssignment;
use mcb_domain::value_objects::ids::IssueLabelAssignmentId;

impl From<issue_label_assignment::Model> for IssueLabelAssignment {
    fn from(m: issue_label_assignment::Model) -> Self {
        Self {
            id: IssueLabelAssignmentId::from(format!("{}:{}", m.issue_id, m.label_id).as_str()),
            issue_id: m.issue_id,
            label_id: m.label_id,
            created_at: m.created_at,
        }
    }
}

impl From<IssueLabelAssignment> for issue_label_assignment::ActiveModel {
    fn from(e: IssueLabelAssignment) -> Self {
        Self {
            issue_id: ActiveValue::Set(e.issue_id),
            label_id: ActiveValue::Set(e.label_id),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_issue_label_assignment() -> issue_label_assignment::Model {
        issue_label_assignment::Model {
            issue_id: "ref_issue_id_001".into(),
            label_id: "ref_label_id_001".into(),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_issue_label_assignment() {
        let model = sample_issue_label_assignment();
        let model_val = model.issue_id.clone();

        // Model → Domain
        let domain: IssueLabelAssignment = model.into();
        assert_eq!(domain.issue_id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: issue_label_assignment::ActiveModel = domain.into();
    }
}
