//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::issue_comment;
use mcb_domain::entities::IssueComment;

impl From<issue_comment::Model> for IssueComment {
    fn from(m: issue_comment::Model) -> Self {
        Self {
            id: m.id,
            issue_id: m.issue_id,
            author_id: m.author_id,
            content: m.content,
            created_at: m.created_at,
        }
    }
}

impl From<IssueComment> for issue_comment::ActiveModel {
    fn from(e: IssueComment) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            issue_id: ActiveValue::Set(e.issue_id),
            author_id: ActiveValue::Set(e.author_id),
            content: ActiveValue::Set(e.content),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_issue_comment() -> issue_comment::Model {
        issue_comment::Model {
            id: "issue_comment_test_001".into(),
            issue_id: "ref_issue_id_001".into(),
            author_id: "ref_author_id_001".into(),
            content: "test_content".into(),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_issue_comment() {
        let model = sample_issue_comment();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: IssueComment = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: issue_comment::ActiveModel = domain.into();
    }
}
