//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::observation;
use mcb_domain::entities::observation::{Observation, ObservationType};

impl From<observation::Model> for Observation {
    fn from(m: observation::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            content: m.content,
            content_hash: m.content_hash,
            created_at: m.created_at,
            embedding_id: m.embedding_id,
            tags: m
                .tags
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
            r#type: m
                .observation_type
                .as_deref()
                .and_then(|s| s.parse::<ObservationType>().ok())
                .unwrap_or(ObservationType::Context),
            metadata: m
                .metadata
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
        }
    }
}

impl From<Observation> for observation::ActiveModel {
    fn from(e: Observation) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            content: ActiveValue::Set(e.content),
            content_hash: ActiveValue::Set(e.content_hash),
            created_at: ActiveValue::Set(e.created_at),
            embedding_id: ActiveValue::Set(e.embedding_id),
            tags: ActiveValue::Set(Some(
                serde_json::to_string(&e.tags).unwrap_or_else(|_| "[]".into()),
            )),
            observation_type: ActiveValue::Set(Some(e.r#type.to_string())),
            metadata: ActiveValue::Set(Some(
                serde_json::to_string(&e.metadata).unwrap_or_else(|_| "{}".into()),
            )),
        }
    }
}
