//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::observation;
use mcb_domain::entities::observation::{Observation, ObservationType};

impl From<observation::Model> for Observation {
    fn from(m: observation::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            content: m.content,
            content_hash: m.content_hash,
            created_at: m.created_at,
            embedding_id: m.embedding_id,
            tags: m
                .tags
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
            r#type: m
                .observation_type
                .as_deref()
                .and_then(|s| s.parse::<ObservationType>().ok())
                .unwrap_or(ObservationType::Context),
            metadata: m
                .metadata
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default(),
        }
    }
}

impl From<Observation> for observation::ActiveModel {
    fn from(e: Observation) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            content: ActiveValue::Set(e.content),
            content_hash: ActiveValue::Set(e.content_hash),
            created_at: ActiveValue::Set(e.created_at),
            embedding_id: ActiveValue::Set(e.embedding_id),
            tags: ActiveValue::Set(Some(
                serde_json::to_string(&e.tags).unwrap_or_else(|_| "[]".into()),
            )),
            observation_type: ActiveValue::Set(Some(e.r#type.to_string())),
            metadata: ActiveValue::Set(Some(
                serde_json::to_string(&e.metadata).unwrap_or_else(|_| "{}".into()),
            )),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_observation() -> observation::Model {
        observation::Model {
            id: "observation_test_001".into(),
            project_id: "ref_project_id_001".into(),
            content: "test_content".into(),
            content_hash: "hash_observation_001".into(),
            tags: Some(r#"["tag1","tag2"]"#.into()),
            observation_type: Some("Context".into()),
            metadata: Some(r#"{"key":"val"}"#.into()),
            created_at: 1_700_000_000,
            embedding_id: Some("test_embedding_id".into()),
        }
    }

    #[test]
    fn round_trip_observation() {
        let model = sample_observation();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Observation = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: observation::ActiveModel = domain.into();
    }
}
