//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::organization;
use mcb_domain::entities::Organization;

impl From<organization::Model> for Organization {
    fn from(m: organization::Model) -> Self {
        Self {
            id: m.id,
            name: m.name,
            slug: m.slug,
            settings_json: m.settings_json,
            created_at: m.created_at,
            updated_at: m.updated_at,
        }
    }
}

impl From<Organization> for organization::ActiveModel {
    fn from(e: Organization) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            name: ActiveValue::Set(e.name),
            slug: ActiveValue::Set(e.slug),
            settings_json: ActiveValue::Set(e.settings_json),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_organization() -> organization::Model {
        organization::Model {
            id: "organization_test_001".into(),
            name: "test_name".into(),
            slug: "test-organization".into(),
            settings_json: "{}".into(),
            created_at: 1_700_000_000,
            updated_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_organization() {
        let model = sample_organization();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Organization = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: organization::ActiveModel = domain.into();
    }
}
