//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::organization;
use mcb_domain::entities::Organization;

impl From<organization::Model> for Organization {
    fn from(m: organization::Model) -> Self {
        Self {
            id: m.id,
            name: m.name,
            slug: m.slug,
            settings_json: m.settings_json,
            created_at: m.created_at,
            updated_at: m.updated_at,
        }
    }
}

impl From<Organization> for organization::ActiveModel {
    fn from(e: Organization) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            name: ActiveValue::Set(e.name),
            slug: ActiveValue::Set(e.slug),
            settings_json: ActiveValue::Set(e.settings_json),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
        }
    }
}
