//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::plan;
use mcb_domain::entities::Plan;
use mcb_domain::entities::plan::PlanStatus;

impl From<plan::Model> for Plan {
    fn from(m: plan::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            title: m.title,
            description: m.description,
            created_by: m.created_by,
            created_at: m.created_at,
            updated_at: m.updated_at,
            status: m.status.parse::<PlanStatus>().unwrap_or(PlanStatus::Draft),
        }
    }
}

impl From<Plan> for plan::ActiveModel {
    fn from(e: Plan) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            title: ActiveValue::Set(e.title),
            description: ActiveValue::Set(e.description),
            created_by: ActiveValue::Set(e.created_by),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            status: ActiveValue::Set(e.status.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_plan() -> plan::Model {
        plan::Model {
            id: "plan_test_001".into(),
            org_id: "ref_org_id_001".into(),
            project_id: "ref_project_id_001".into(),
            title: "test_title".into(),
            description: "test_description".into(),
            status: "Draft".into(),
            created_by: "test_created_by".into(),
            created_at: 1_700_000_000,
            updated_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_plan() {
        let model = sample_plan();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Plan = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: plan::ActiveModel = domain.into();
    }
}
