//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::plan;
use mcb_domain::entities::Plan;
use mcb_domain::entities::plan::PlanStatus;

impl From<plan::Model> for Plan {
    fn from(m: plan::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            title: m.title,
            description: m.description,
            created_by: m.created_by,
            created_at: m.created_at,
            updated_at: m.updated_at,
            status: m.status.parse::<PlanStatus>().unwrap_or(PlanStatus::Draft),
        }
    }
}

impl From<Plan> for plan::ActiveModel {
    fn from(e: Plan) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            title: ActiveValue::Set(e.title),
            description: ActiveValue::Set(e.description),
            created_by: ActiveValue::Set(e.created_by),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            status: ActiveValue::Set(e.status.to_string()),
        }
    }
}
