//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::plan_review;
use mcb_domain::entities::plan::{PlanReview, ReviewVerdict};

impl From<plan_review::Model> for PlanReview {
    fn from(m: plan_review::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            plan_version_id: m.plan_version_id,
            reviewer_id: m.reviewer_id,
            feedback: m.feedback,
            created_at: m.created_at,
            verdict: m
                .verdict
                .parse::<ReviewVerdict>()
                .unwrap_or(ReviewVerdict::NeedsRevision),
        }
    }
}

impl From<PlanReview> for plan_review::ActiveModel {
    fn from(e: PlanReview) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            plan_version_id: ActiveValue::Set(e.plan_version_id),
            reviewer_id: ActiveValue::Set(e.reviewer_id),
            feedback: ActiveValue::Set(e.feedback),
            created_at: ActiveValue::Set(e.created_at),
            verdict: ActiveValue::Set(e.verdict.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_plan_review() -> plan_review::Model {
        plan_review::Model {
            id: "plan_review_test_001".into(),
            org_id: "ref_org_id_001".into(),
            plan_version_id: "ref_plan_version_id_001".into(),
            reviewer_id: "ref_reviewer_id_001".into(),
            verdict: "NeedsRevision".into(),
            feedback: "test_feedback".into(),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_plan_review() {
        let model = sample_plan_review();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: PlanReview = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: plan_review::ActiveModel = domain.into();
    }
}
