//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::plan_version;
use mcb_domain::entities::plan::PlanVersion;

impl From<plan_version::Model> for PlanVersion {
    fn from(m: plan_version::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            plan_id: m.plan_id,
            version_number: m.version_number,
            content_json: m.content_json,
            change_summary: m.change_summary,
            created_by: m.created_by,
            created_at: m.created_at,
        }
    }
}

impl From<PlanVersion> for plan_version::ActiveModel {
    fn from(e: PlanVersion) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            plan_id: ActiveValue::Set(e.plan_id),
            version_number: ActiveValue::Set(e.version_number),
            content_json: ActiveValue::Set(e.content_json),
            change_summary: ActiveValue::Set(e.change_summary),
            created_by: ActiveValue::Set(e.created_by),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}
