//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::project_issue;
use mcb_domain::entities::ProjectIssue;
use mcb_domain::entities::project::{IssueStatus, IssueType};

impl From<project_issue::Model> for ProjectIssue {
    fn from(m: project_issue::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            created_by: m.created_by,
            phase_id: m.phase_id,
            title: m.title,
            description: m.description,
            assignee: m.assignee,
            estimated_minutes: m.estimated_minutes,
            actual_minutes: m.actual_minutes,
            notes: m.notes,
            design: m.design,
            parent_issue_id: m.parent_issue_id,
            created_at: m.created_at,
            updated_at: m.updated_at,
            closed_at: m.closed_at,
            closed_reason: m.closed_reason,
            issue_type: m.issue_type.parse::<IssueType>().unwrap_or(IssueType::Task),
            status: m.status.parse::<IssueStatus>().unwrap_or(IssueStatus::Open),
            priority: m.priority as i32,
            labels: serde_json::from_str(&m.labels).unwrap_or_default(),
        }
    }
}

impl From<ProjectIssue> for project_issue::ActiveModel {
    fn from(e: ProjectIssue) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            created_by: ActiveValue::Set(e.created_by),
            phase_id: ActiveValue::Set(e.phase_id),
            title: ActiveValue::Set(e.title),
            description: ActiveValue::Set(e.description),
            assignee: ActiveValue::Set(e.assignee),
            estimated_minutes: ActiveValue::Set(e.estimated_minutes),
            actual_minutes: ActiveValue::Set(e.actual_minutes),
            notes: ActiveValue::Set(e.notes),
            design: ActiveValue::Set(e.design),
            parent_issue_id: ActiveValue::Set(e.parent_issue_id),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            closed_at: ActiveValue::Set(e.closed_at),
            closed_reason: ActiveValue::Set(e.closed_reason),
            issue_type: ActiveValue::Set(e.issue_type.to_string()),
            status: ActiveValue::Set(e.status.to_string()),
            priority: ActiveValue::Set(i64::from(e.priority)),
            labels: ActiveValue::Set(
                serde_json::to_string(&e.labels).unwrap_or_else(|_| "[]".into()),
            ),
        }
    }
}
