//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::project_decision;
use mcb_domain::entities::project::ProjectDecision;

impl From<project_decision::Model> for ProjectDecision {
    fn from(m: project_decision::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            issue_id: m.issue_id,
            title: m.title,
            context: m.context,
            decision: m.decision,
            consequences: m.consequences,
            created_at: m.created_at,
        }
    }
}

impl From<ProjectDecision> for project_decision::ActiveModel {
    fn from(e: ProjectDecision) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            issue_id: ActiveValue::Set(e.issue_id),
            title: ActiveValue::Set(e.title),
            context: ActiveValue::Set(e.context),
            decision: ActiveValue::Set(e.decision),
            consequences: ActiveValue::Set(e.consequences),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_project_decision() -> project_decision::Model {
        project_decision::Model {
            id: "project_decision_test_001".into(),
            project_id: "ref_project_id_001".into(),
            issue_id: Some("test_issue_id".into()),
            title: "test_title".into(),
            context: "test_context".into(),
            decision: "test_decision".into(),
            consequences: "test_consequences".into(),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_project_decision() {
        let model = sample_project_decision();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: ProjectDecision = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: project_decision::ActiveModel = domain.into();
    }
}
