//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::project;
use mcb_domain::entities::Project;

impl From<project::Model> for Project {
    fn from(m: project::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            name: m.name,
            path: m.path,
            created_at: m.created_at,
            updated_at: m.updated_at,
        }
    }
}

impl From<Project> for project::ActiveModel {
    fn from(e: Project) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            name: ActiveValue::Set(e.name),
            path: ActiveValue::Set(e.path),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_project() -> project::Model {
        project::Model {
            id: "project_test_001".into(),
            org_id: "ref_org_id_001".into(),
            name: "test_name".into(),
            path: "/tmp/test-path".into(),
            created_at: 1_700_000_000,
            updated_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_project() {
        let model = sample_project();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Project = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: project::ActiveModel = domain.into();
    }
}
