//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::project_phase;
use mcb_domain::entities::project::{PhaseStatus, ProjectPhase};

impl From<project_phase::Model> for ProjectPhase {
    fn from(m: project_phase::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            name: m.name,
            description: m.description,
            started_at: m.started_at,
            completed_at: m.completed_at,
            created_at: m.created_at,
            updated_at: m.updated_at,
            sequence: m.sequence as i32,
            status: m
                .status
                .parse::<PhaseStatus>()
                .unwrap_or(PhaseStatus::Planned),
        }
    }
}

impl From<ProjectPhase> for project_phase::ActiveModel {
    fn from(e: ProjectPhase) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            name: ActiveValue::Set(e.name),
            description: ActiveValue::Set(e.description),
            started_at: ActiveValue::Set(e.started_at),
            completed_at: ActiveValue::Set(e.completed_at),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            sequence: ActiveValue::Set(i64::from(e.sequence)),
            status: ActiveValue::Set(e.status.to_string()),
        }
    }
}
