//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::repository;
use mcb_domain::entities::Repository;
use mcb_domain::entities::repository::VcsType;

impl From<repository::Model> for Repository {
    fn from(m: repository::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            project_id: m.project_id,
            name: m.name,
            url: m.url,
            local_path: m.local_path,
            created_at: m.created_at,
            updated_at: m.updated_at,
            vcs_type: m.vcs_type.parse::<VcsType>().unwrap_or(VcsType::Git),
        }
    }
}

impl From<Repository> for repository::ActiveModel {
    fn from(e: Repository) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            project_id: ActiveValue::Set(e.project_id),
            name: ActiveValue::Set(e.name),
            url: ActiveValue::Set(e.url),
            local_path: ActiveValue::Set(e.local_path),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            vcs_type: ActiveValue::Set(e.vcs_type.to_string()),
            origin_context: ActiveValue::NotSet,
        }
    }
}
