//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::session_summary;
use mcb_domain::entities::memory::{OriginContext, SessionSummary};

impl From<session_summary::Model> for SessionSummary {
    fn from(m: session_summary::Model) -> Self {
        Self {
            id: m.id,
            project_id: m.project_id,
            session_id: m.session_id,
            created_at: m.created_at,
            org_id: m.org_id.unwrap_or_default(),
            topics: m
                .topics
                .as_deref()
                .and_then(|s| serde_json::from_str(s).map_err(|e| tracing::warn!(field = "topics", error = %e, "malformed JSON in DB column")).ok())
                .unwrap_or_default(),
            decisions: m
                .decisions
                .as_deref()
                .and_then(|s| serde_json::from_str(s).map_err(|e| tracing::warn!(field = "decisions", error = %e, "malformed JSON in DB column")).ok())
                .unwrap_or_default(),
            next_steps: m
                .next_steps
                .as_deref()
                .and_then(|s| serde_json::from_str(s).map_err(|e| tracing::warn!(field = "next_steps", error = %e, "malformed JSON in DB column")).ok())
                .unwrap_or_default(),
            key_files: m
                .key_files
                .as_deref()
                .and_then(|s| serde_json::from_str(s).map_err(|e| tracing::warn!(field = "key_files", error = %e, "malformed JSON in DB column")).ok())
                .unwrap_or_default(),
            origin_context: m
                .origin_context
                .as_deref()
                .and_then(|s| serde_json::from_str::<OriginContext>(s).map_err(|e| tracing::warn!(field = "origin_context", error = %e, "malformed JSON in DB column")).ok()),
        }
    }
}

impl From<SessionSummary> for session_summary::ActiveModel {
    fn from(e: SessionSummary) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            project_id: ActiveValue::Set(e.project_id),
            session_id: ActiveValue::Set(e.session_id),
            created_at: ActiveValue::Set(e.created_at),
            org_id: ActiveValue::Set(Some(e.org_id)),
            topics: ActiveValue::Set(Some(
                serde_json::to_string(&e.topics).unwrap_or_else(|_| "[]".into()),
            )),
            decisions: ActiveValue::Set(Some(
                serde_json::to_string(&e.decisions).unwrap_or_else(|_| "[]".into()),
            )),
            next_steps: ActiveValue::Set(Some(
                serde_json::to_string(&e.next_steps).unwrap_or_else(|_| "[]".into()),
            )),
            key_files: ActiveValue::Set(Some(
                serde_json::to_string(&e.key_files).unwrap_or_else(|_| "[]".into()),
            )),
            origin_context: ActiveValue::Set(
                e.origin_context
                    .as_ref()
                    .and_then(|oc| serde_json::to_string(oc).ok()),
            ),
            repo_id: ActiveValue::NotSet,
        }
    }
}
