//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::team_member;
use mcb_domain::entities::team::{TeamMember, TeamMemberRole};
use mcb_domain::value_objects::ids::TeamMemberId;

impl From<team_member::Model> for TeamMember {
    fn from(m: team_member::Model) -> Self {
        Self {
            id: TeamMemberId::from(format!("{}:{}", m.team_id, m.user_id).as_str()),
            team_id: m.team_id,
            user_id: m.user_id,
            joined_at: m.joined_at,
            role: m
                .role
                .parse::<TeamMemberRole>()
                .unwrap_or(TeamMemberRole::Member),
        }
    }
}

impl From<TeamMember> for team_member::ActiveModel {
    fn from(e: TeamMember) -> Self {
        Self {
            team_id: ActiveValue::Set(e.team_id),
            user_id: ActiveValue::Set(e.user_id),
            joined_at: ActiveValue::Set(e.joined_at),
            role: ActiveValue::Set(e.role.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_team_member() -> team_member::Model {
        team_member::Model {
            team_id: "ref_team_id_001".into(),
            user_id: "ref_user_id_001".into(),
            role: "Member".into(),
            joined_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_team_member() {
        let model = sample_team_member();
        let model_val = model.team_id.clone();

        // Model → Domain
        let domain: TeamMember = model.into();
        assert_eq!(domain.team_id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: team_member::ActiveModel = domain.into();
    }
}
