//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::team;
use mcb_domain::entities::Team;

impl From<team::Model> for Team {
    fn from(m: team::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            name: m.name,
            created_at: m.created_at,
        }
    }
}

impl From<Team> for team::ActiveModel {
    fn from(e: Team) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            name: ActiveValue::Set(e.name),
            created_at: ActiveValue::Set(e.created_at),
        }
    }
}
