//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::tool_call;
use mcb_domain::entities::ToolCall;

impl From<tool_call::Model> for ToolCall {
    fn from(m: tool_call::Model) -> Self {
        Self {
            id: m.id,
            session_id: m.session_id,
            tool_name: m.tool_name,
            params_summary: m.params_summary,
            error_message: m.error_message,
            duration_ms: m.duration_ms,
            created_at: m.created_at,
            success: m.success != 0,
        }
    }
}

impl From<ToolCall> for tool_call::ActiveModel {
    fn from(e: ToolCall) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            session_id: ActiveValue::Set(e.session_id),
            tool_name: ActiveValue::Set(e.tool_name),
            params_summary: ActiveValue::Set(e.params_summary),
            error_message: ActiveValue::Set(e.error_message),
            duration_ms: ActiveValue::Set(e.duration_ms),
            created_at: ActiveValue::Set(e.created_at),
            success: ActiveValue::Set(i64::from(e.success)),
            org_id: ActiveValue::NotSet,
            project_id: ActiveValue::NotSet,
            repo_id: ActiveValue::NotSet,
        }
    }
}
