//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::tool_call;
use mcb_domain::entities::ToolCall;

impl From<tool_call::Model> for ToolCall {
    fn from(m: tool_call::Model) -> Self {
        Self {
            id: m.id,
            session_id: m.session_id,
            tool_name: m.tool_name,
            params_summary: m.params_summary,
            error_message: m.error_message,
            duration_ms: m.duration_ms,
            created_at: m.created_at,
            success: m.success != 0,
        }
    }
}

impl From<ToolCall> for tool_call::ActiveModel {
    fn from(e: ToolCall) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            session_id: ActiveValue::Set(e.session_id),
            tool_name: ActiveValue::Set(e.tool_name),
            params_summary: ActiveValue::Set(e.params_summary),
            error_message: ActiveValue::Set(e.error_message),
            duration_ms: ActiveValue::Set(e.duration_ms),
            created_at: ActiveValue::Set(e.created_at),
            success: ActiveValue::Set(i64::from(e.success)),
            org_id: ActiveValue::NotSet,
            project_id: ActiveValue::NotSet,
            repo_id: ActiveValue::NotSet,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_tool_call() -> tool_call::Model {
        tool_call::Model {
            id: "tool_call_test_001".into(),
            org_id: None,
            project_id: None,
            repo_id: None,
            session_id: "ref_session_id_001".into(),
            tool_name: "test_tool_name".into(),
            params_summary: Some("test_params_summary".into()),
            success: 1,
            error_message: Some("test_error_message".into()),
            duration_ms: Some(1500),
            created_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_tool_call() {
        let model = sample_tool_call();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: ToolCall = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: tool_call::ActiveModel = domain.into();
    }
}
