//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT


use sea_orm::ActiveValue;

use crate::database::seaorm::entities::user;
use mcb_domain::entities::User;
use mcb_domain::entities::user::UserRole;

impl From<user::Model> for User {
    fn from(m: user::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            email: m.email,
            display_name: m.display_name,
            api_key_hash: m.api_key_hash,
            created_at: m.created_at,
            updated_at: m.updated_at,
            role: m.role.parse::<UserRole>().unwrap_or_default(),
        }
    }
}

impl From<User> for user::ActiveModel {
    fn from(e: User) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            email: ActiveValue::Set(e.email),
            display_name: ActiveValue::Set(e.display_name),
            api_key_hash: ActiveValue::Set(e.api_key_hash),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            role: ActiveValue::Set(e.role.to_string()),
        }
    }
}
