//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::user;
use mcb_domain::entities::User;
use mcb_domain::entities::user::UserRole;

impl From<user::Model> for User {
    fn from(m: user::Model) -> Self {
        Self {
            id: m.id,
            org_id: m.org_id,
            email: m.email,
            display_name: m.display_name,
            api_key_hash: m.api_key_hash,
            created_at: m.created_at,
            updated_at: m.updated_at,
            role: m.role.parse::<UserRole>().unwrap_or_default(),
        }
    }
}

impl From<User> for user::ActiveModel {
    fn from(e: User) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            org_id: ActiveValue::Set(e.org_id),
            email: ActiveValue::Set(e.email),
            display_name: ActiveValue::Set(e.display_name),
            api_key_hash: ActiveValue::Set(e.api_key_hash),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            role: ActiveValue::Set(e.role.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_user() -> user::Model {
        user::Model {
            id: "user_test_001".into(),
            org_id: "ref_org_id_001".into(),
            email: "test@example.com".into(),
            display_name: "test_display_name".into(),
            role: "Default".into(),
            api_key_hash: Some("test_api_key_hash".into()),
            created_at: 1_700_000_000,
            updated_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_user() {
        let model = sample_user();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: User = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: user::ActiveModel = domain.into();
    }
}
