//! ⚠️ GENERATED by `make codegen-conversions` — DO NOT EDIT

use sea_orm::ActiveValue;

use crate::database::seaorm::entities::worktree;
use mcb_domain::entities::Worktree;
use mcb_domain::entities::worktree::WorktreeStatus;

impl From<worktree::Model> for Worktree {
    fn from(m: worktree::Model) -> Self {
        Self {
            id: m.id,
            repository_id: m.repository_id,
            branch_id: m.branch_id,
            path: m.path,
            assigned_agent_id: m.assigned_agent_id,
            created_at: m.created_at,
            updated_at: m.updated_at,
            status: m
                .status
                .parse::<WorktreeStatus>()
                .unwrap_or(WorktreeStatus::Active),
        }
    }
}

impl From<Worktree> for worktree::ActiveModel {
    fn from(e: Worktree) -> Self {
        Self {
            id: ActiveValue::Set(e.id),
            repository_id: ActiveValue::Set(e.repository_id),
            branch_id: ActiveValue::Set(e.branch_id),
            path: ActiveValue::Set(e.path),
            assigned_agent_id: ActiveValue::Set(e.assigned_agent_id),
            created_at: ActiveValue::Set(e.created_at),
            updated_at: ActiveValue::Set(e.updated_at),
            status: ActiveValue::Set(e.status.to_string()),
            org_id: ActiveValue::NotSet,
            project_id: ActiveValue::NotSet,
            origin_context: ActiveValue::NotSet,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_worktree() -> worktree::Model {
        worktree::Model {
            id: "worktree_test_001".into(),
            org_id: None,
            project_id: None,
            repository_id: "ref_repository_id_001".into(),
            branch_id: "ref_branch_id_001".into(),
            path: "/tmp/test-path".into(),
            status: "Active".into(),
            assigned_agent_id: Some("test_assigned_agent_id".into()),
            origin_context: None,
            created_at: 1_700_000_000,
            updated_at: 1_700_000_000,
        }
    }

    #[test]
    fn round_trip_worktree() {
        let model = sample_worktree();
        let model_val = model.id.clone();

        // Model → Domain
        let domain: Worktree = model.into();
        assert_eq!(domain.id, model_val);

        // Domain → ActiveModel (should not panic)
        let _active: worktree::ActiveModel = domain.into();
    }
}
