pub const DEFAULT_NATS_CLIENT_NAME: &str = "mcb-context-browser";
pub const NATS_CONNECT_TIMEOUT_SECS: u64 = 10;
pub const NATS_REQUEST_TIMEOUT_SECS: u64 = 5;
pub const EVENT_BUS_BUFFER_SIZE: usize = 1000;
pub const EVENT_BUS_DEFAULT_CAPACITY: usize = 1024;
pub const EVENT_BUS_CONNECTION_TIMEOUT_MS: u64 = 5000;
pub const EVENT_BUS_MAX_RECONNECT_ATTEMPTS: u32 = 5;
