/// Constant value for `HEALTH_CHECK_TIMEOUT_SECS`.
pub const HEALTH_CHECK_TIMEOUT_SECS: u64 = 5;
/// Constant value for `HEALTH_CHECK_INTERVAL_SECS`.
pub const HEALTH_CHECK_INTERVAL_SECS: u64 = 30;
/// Constant value for `HEALTH_CHECK_FAILURE_THRESHOLD`.
pub const HEALTH_CHECK_FAILURE_THRESHOLD: u32 = 3;
