pub const DAEMON_CHECK_INTERVAL_SECS: u64 = 30;
pub const DAEMON_RESTART_DELAY_SECS: u64 = 5;
pub const DAEMON_MAX_RESTART_ATTEMPTS: u32 = 3;
pub const GRACEFUL_SHUTDOWN_TIMEOUT_SECS: u64 = 30;
pub const FORCE_SHUTDOWN_TIMEOUT_SECS: u64 = 10;
pub const SIGNAL_POLL_INTERVAL_MS: u64 = 100;
