pub const CIRCUIT_BREAKER_FAILURE_THRESHOLD: u32 = 5;
pub const CIRCUIT_BREAKER_TIMEOUT_SECS: u64 = 60;
pub const CIRCUIT_BREAKER_SUCCESS_THRESHOLD: u32 = 3;
pub const RATE_LIMITER_DEFAULT_RPS: u32 = 100;
pub const RATE_LIMITER_DEFAULT_BURST: u32 = 200;
pub const DEFAULT_RETRY_ATTEMPTS: u32 = 3;
pub const DEFAULT_RETRY_DELAY_MS: u64 = 1000;
