/// Constant value for `CIRCUIT_BREAKER_FAILURE_THRESHOLD`.
pub const CIRCUIT_BREAKER_FAILURE_THRESHOLD: u32 = 5;
/// Constant value for `CIRCUIT_BREAKER_TIMEOUT_SECS`.
pub const CIRCUIT_BREAKER_TIMEOUT_SECS: u64 = 60;
/// Constant value for `CIRCUIT_BREAKER_SUCCESS_THRESHOLD`.
pub const CIRCUIT_BREAKER_SUCCESS_THRESHOLD: u32 = 3;
/// Constant value for `RATE_LIMITER_DEFAULT_RPS`.
pub const RATE_LIMITER_DEFAULT_RPS: u32 = 100;
/// Constant value for `RATE_LIMITER_DEFAULT_BURST`.
pub const RATE_LIMITER_DEFAULT_BURST: u32 = 200;
/// Constant value for `DEFAULT_RETRY_ATTEMPTS`.
pub const DEFAULT_RETRY_ATTEMPTS: u32 = 3;
/// Constant value for `DEFAULT_RETRY_DELAY_MS`.
pub const DEFAULT_RETRY_DELAY_MS: u64 = 1000;
