//! Repository ports for data persistence.
//!
//! All repository traits use `#[async_trait]` and require `Send + Sync`.
//! Standard CRUD traits are generated by `define_crud_port!` / `define_readonly_port!`
//! macros to eliminate boilerplate.
//!
//! Organized into submodules by domain aggregate.

/// Agent session/event/checkpoint repository ports.
pub mod agent;
/// Authentication repository ports.
pub mod auth;
/// File hash tracking repository ports.
pub mod file_hash;
/// Indexing operation repository ports.
pub mod index;
/// Issue repository ports (issue, comment, label).
pub mod issue;
/// Memory/observation repository ports.
pub mod memory;
/// Organization repository ports (org, user, team, API key).
pub mod org;
/// Plan repository ports (plan, version, review).
pub mod plan;
/// Project repository ports.
pub mod project;
/// VCS repository ports (repository, branch, worktree, agent assignments).
pub mod vcs;
/// Workflow session and transition repository ports.
pub mod workflow;

// Re-exports for canonical access via `ports::repositories::{...}`
pub use agent::{
    AgentCheckpointRepository, AgentEventRepository, AgentRepository, AgentSessionQuery,
    AgentSessionRepository,
};
pub use auth::{ApiKeyInfo, AuthRepositoryPort, UserWithApiKey};
pub use file_hash::FileHashRepository;
pub use index::{IndexRepository, IndexStats};
pub use issue::{
    IssueCommentRegistry, IssueEntityRepository, IssueLabelAssignmentManager, IssueLabelRegistry,
    IssueRegistry,
};
pub use memory::{FtsSearchResult, MemoryRepository};
pub use org::{
    ApiKeyRegistry, OrgEntityRepository, OrgRegistry, TeamMemberManager, TeamRegistry, UserRegistry,
};
pub use plan::{PlanEntityRepository, PlanRegistry, PlanReviewRegistry, PlanVersionRegistry};
pub use project::ProjectRepository;
pub use vcs::{
    AgentAssignmentManager, VcsBranchRegistry, VcsEntityRepository, VcsRepositoryRegistry,
    VcsWorktreeRegistry,
};
pub use workflow::{TransitionRepository, WorkflowSessionRepository};
