//! Repository ports for data persistence.
//!
//! All repository traits use `#[async_trait]` and require `Send + Sync`.
//! Standard CRUD traits are generated by `define_crud_port!` / `define_readonly_port!`
//! macros to eliminate boilerplate.
//!
//! Organized into submodules by domain aggregate.

/// Agent session/event/checkpoint repository ports.
mod agent;
/// Authentication repository ports.
mod auth;
/// File hash tracking repository ports.
mod file_hash;
/// Indexing operation repository ports.
mod index;
/// Issue repository ports (issue, comment, label).
mod issue;
/// Memory/observation repository ports.
mod memory;
/// Organization repository ports (org, user, team, API key).
mod org;
/// Plan repository ports (plan, version, review).
mod plan;
/// Project repository ports.
mod project;
/// VCS repository ports (repository, branch, worktree, agent assignments).
mod vcs;
/// Workflow session and transition repository ports.
mod workflow;

pub use agent::*;
pub use auth::*;
pub use file_hash::*;
pub use index::*;
pub use issue::*;
pub use memory::*;
pub use org::*;
pub use plan::*;
pub use project::*;
pub use vcs::*;
pub use workflow::*;
