#!/usr/bin/env python3
"""Generate domain ↔ SeaORM conversion files from config/conversions.toml.

Reads the TOML config and generates one Rust file per entity with:
- From<entity::Model> for DomainType
- From<DomainType> for entity::ActiveModel

Usage: python3 scripts/codegen-conversions.py

Copyright (c) 2026 Marlon Costa. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import re
import tomllib
from collections.abc import Callable
from pathlib import Path
from typing import NotRequired, Required, TypedDict

from flext_core import t


class ConverterConfig(TypedDict, total=False):
    type: Required[str]
    domain_field: str
    default: str
    enum_type: str
    object_type: str
    from_model: str


EntityConfig = TypedDict(
    "EntityConfig",
    {
        "domain": str,
        "import": str,
        "entity": str,
        "fields": list[str],
        "extra_imports": NotRequired[list[str]],
        "not_set": NotRequired[list[str]],
        "convert": NotRequired[dict[str, ConverterConfig]],
    },
)

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "conversions.toml"
OUTPUT_DIR = (
    ROOT / "crates" / "mcb-providers" / "src" / "database" / "seaorm" / "conversions"
)

GENERATED_HEADER = "//! ⚠️ GENERATED by `make build WHAT=codegen ACT=conversions APPLY=Y` — DO NOT EDIT\n"
ENTITIES_DIR = (
    ROOT / "crates" / "mcb-providers" / "src" / "database" / "seaorm" / "entities"
)

# Regex to extract `pub field: Type` from SeaORM entity Model structs
_MODEL_FIELD_RE = re.compile(r"^\s*pub\s+(\w+):\s+(.+?)\s*,?\s*$")


def parse_entity_model_fields(entity_module: str) -> dict[str, str]:
    """Parse the SeaORM entity .rs file to extract Model field names and types.

    Returns a dict mapping field_name -> rust_type (e.g. 'String', 'Option<String>', 'i64').

    Returns:
        The resulting ``dict[str, str]``.
    """
    # Entity files use plural names; the mod.rs re-exports as singular.
    # Read mod.rs to find the mapping: `pub use {plural} as {singular};`
    mod_rs = ENTITIES_DIR / "mod.rs"
    plural_name = entity_module  # fallback
    for line in mod_rs.read_text().splitlines():
        m = re.match(rf"^pub use (\w+) as {re.escape(entity_module)};$", line.strip())
        if m:
            plural_name = m.group(1)
            break

    entity_file = ENTITIES_DIR / f"{plural_name}.rs"
    if not entity_file.exists():
        return {}

    text = entity_file.read_text()
    # Extract the Model struct body
    in_model = False
    brace_depth = 0
    fields: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("pub struct Model"):
            in_model = True
            brace_depth = 0
        if in_model:
            brace_depth += stripped.count("{") - stripped.count("}")
            fm = _MODEL_FIELD_RE.match(line)
            if fm:
                fields[fm.group(1)] = fm.group(2)
            if brace_depth <= 0 and "}" in stripped and in_model and fields:
                break
    return fields


_JSON_WARN_FROM_OPT = (
    "                .as_deref()\n"
    '                .and_then(|s| serde_json::from_str(s).map_err(|e| tracing::warn!(field = "{field}", error = %e, "malformed JSON in DB column")).ok())\n'
)

_FIXED_CTYPE_TEST_VALUES: dict[str, str] = {
    "bool": "1",
    "bool_opt": "Some(1)",
    "opt_bool": "Some(1)",
    "int_cast": "2",
    "opt_int_cast": "Some(3)",
    "json_array": 'Some(r#"["tag1","tag2"]"#.into())',
    "json_array_required": 'r#"["label-a"]"#.into()',
    "json_object": 'Some(r#"{"key":"val"}"#.into())',
    "json_object_opt": 'Some(r#"{"key":"val"}"#.into())',
    "json_value": 'r#"{"test":true}"#.into()',
    "unwrap_default": 'Some("test_unwrap".into())',
    "computed": '"computed_skip".into()',
}


def _enum_variant(default: str) -> str:
    """Extract the variant string, e.g. "AgentType::Sisyphus" -> "Sisyphus".

    Returns:
        The resulting ``str``.
    """
    return default.split("::")[-1] if default else "Default"


def _converter_test_value(ctype: str, conv: ConverterConfig) -> str | None:
    """Return the converter-driven test value, or ``None`` when type-based.

    Returns:
        The resulting ``str | None``.
    """
    if ctype == "enum":
        return f'"{_enum_variant(conv.get("default", ""))}".into()'
    if ctype == "enum_opt":
        return f'Some("{_enum_variant(conv.get("default", ""))}".into())'
    return _FIXED_CTYPE_TEST_VALUES.get(ctype)


def _named_string_test_value(field_name: str, entity_name: str) -> str | None:
    """Return the test value for exactly-named string fields.

    Returns:
        The resulting ``str | None``.
    """
    named = {
        "id": f'"{entity_name}_test_001".into()',
        "email": '"test@example.com".into()',
        "url": '"https://example.com/repo".into()',
        "slug": f'"test-{entity_name}".into()',
        "path": '"/tmp/test-path".into()',
        "local_path": '"/tmp/test-path".into()',
    }
    return named.get(field_name)


def _suffix_string_test_value(field_name: str, entity_name: str) -> str | None:
    """Return the test value for suffix-named string fields.

    Returns:
        The resulting ``str | None``.
    """
    suffixes = {
        "_id": f'"ref_{field_name}_001".into()',
        "_json": '"{}".into()',
        "_hash": f'"hash_{entity_name}_001".into()',
    }
    for suffix, value in suffixes.items():
        if field_name.endswith(suffix):
            return value
    return None


def _string_test_value(field_name: str, entity_name: str) -> str:
    """Return the test value for a non-optional string field.

    Returns:
        The resulting ``str``.
    """
    named = _named_string_test_value(field_name, entity_name)
    if named is not None:
        return named
    suffix = _suffix_string_test_value(field_name, entity_name)
    if suffix is not None:
        return suffix
    return f'"test_{field_name}".into()'


def _i64_suffix_test_value(field_name: str) -> str | None:
    """Return the test value for suffix-named i64 fields.

    Returns:
        The resulting ``str | None``.
    """
    if field_name.endswith("_at"):
        return "1_700_000_000"
    if field_name.endswith("_ms"):
        return "1500"
    if field_name.endswith("_count"):
        return "5"
    return None


def _i64_test_value(field_name: str) -> str:
    """Return the test value for a non-optional i64 field.

    Returns:
        The resulting ``str``.
    """
    suffix = _i64_suffix_test_value(field_name)
    if suffix is not None:
        return suffix
    named = {"confidence": "85", "priority": "2", "version_number": "1"}
    return named.get(field_name, "1")


def _option_int_test_value(field_name: str) -> str:
    """Return the test value for an optional i64 field.

    Returns:
        The resulting ``str``.
    """
    if field_name.endswith("_at"):
        return "Some(1_700_000_000)"
    if field_name.endswith("_ms"):
        return "Some(1500)"
    return "Some(1)"


def _option_test_value(field_name: str, inner: str) -> str:
    """Return the test value for an optional field by inner type.

    Returns:
        The resulting ``str``.
    """
    if inner == "i64":
        return _option_int_test_value(field_name)
    return f'Some("test_{field_name}".into())'


def _type_test_value(field_name: str, db_type: str, entity_name: str) -> str:
    """Return the type-based default test value for a direct field.

    Returns:
        The resulting ``str``.
    """
    if db_type.startswith("Option<"):
        return _option_test_value(field_name, db_type[len("Option<") : -1])
    if db_type == "String":
        return _string_test_value(field_name, entity_name)
    if db_type == "i64":
        return _i64_test_value(field_name)
    return f'"test_{field_name}".into()'


def _test_value_for_field(
    field_name: str,
    db_type: str,
    entity_name: str,
    convert: dict[str, ConverterConfig],
    not_set: list[str],
) -> str:
    """Generate a realistic test value for a Model field.

    Returns:
        The resulting ``str``.
    """
    if field_name in not_set:
        return "None"

    conv = convert.get(field_name) or {"type": ""}
    converter_value = _converter_test_value(conv.get("type", ""), conv)
    if converter_value is not None:
        return converter_value

    return _type_test_value(field_name, db_type, entity_name)


def _from_model_enum(field: str, domain_field: str, conv: ConverterConfig) -> str:
    if conv.get("default"):
        return f"            {domain_field}: m.{field}.parse::<{conv.get('enum_type', '')}>().unwrap_or({conv.get('default', '')}),"
    return f"            {domain_field}: m.{field}.parse::<{conv.get('enum_type', '')}>().unwrap_or_default(),"


def _from_model_enum_opt(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return (
        f"            {domain_field}: m\n"
        f"                .{field}\n"
        f"                .as_deref()\n"
        f"                .and_then(|s| s.parse::<{conv.get('enum_type', '')}>().ok())\n"
        f"                .unwrap_or({conv.get('default', '')}),"
    )


def _from_model_bool(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field} != 0,"


def _from_model_bool_opt(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field}.is_some_and(|v| v != 0),"


def _from_model_opt_bool(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field}.map(|v| v != 0),"


def _from_model_int_cast(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field} as i32,"


def _from_model_opt_int_cast(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field}.map(|v| v as i32),"


def _from_model_json_opt_deser(field: str, domain_field: str) -> str:
    return (
        f"            {domain_field}: m\n"
        f"                .{field}\n"
        + _JSON_WARN_FROM_OPT.replace("{field}", field)
        + "                .unwrap_or_default(),"
    )


def _from_model_json_array(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return _from_model_json_opt_deser(field, domain_field)


def _from_model_json_object(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return _from_model_json_opt_deser(field, domain_field)


def _from_model_json_array_required(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return (
        f"            {domain_field}: serde_json::from_str(&m.{field})\n"
        f'                .map_err(|e| tracing::warn!(field = "{field}", error = %e, "malformed JSON in DB column"))\n'
        f"                .unwrap_or_default(),"
    )


def _from_model_json_object_opt(field: str, domain_field: str, conv: ConverterConfig) -> str:
    obj_type = conv.get("object_type", "")
    return (
        f"            {domain_field}: m\n"
        f"                .{field}\n"
        f"                .as_deref()\n"
        f'                .and_then(|s| serde_json::from_str::<{obj_type}>(s).map_err(|e| tracing::warn!(field = "{field}", error = %e, "malformed JSON in DB column")).ok()),'
    )


def _from_model_json_value(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return (
        f"            {domain_field}: serde_json::from_str(&m.{field})"
        f".unwrap_or(serde_json::Value::Null),"
    )


def _from_model_unwrap_default(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: m.{field}.unwrap_or_default(),"


def _from_model_computed(field: str, domain_field: str, conv: ConverterConfig) -> str:
    return f"            {domain_field}: {conv.get('from_model', '')},"


_FROM_MODEL_GENERATORS: dict[
    str, Callable[[str, str, ConverterConfig], str],
] = {
    "enum": _from_model_enum,
    "enum_opt": _from_model_enum_opt,
    "bool": _from_model_bool,
    "bool_opt": _from_model_bool_opt,
    "opt_bool": _from_model_opt_bool,
    "int_cast": _from_model_int_cast,
    "opt_int_cast": _from_model_opt_int_cast,
    "json_array": _from_model_json_array,
    "json_array_required": _from_model_json_array_required,
    "json_object": _from_model_json_object,
    "json_object_opt": _from_model_json_object_opt,
    "json_value": _from_model_json_value,
    "unwrap_default": _from_model_unwrap_default,
    "computed": _from_model_computed,
}


def gen_from_model_field(field: str, convert: dict[str, ConverterConfig]) -> str:
    conv = convert.get(field)
    if not conv:
        return f"            {field}: m.{field},"

    domain_field = conv.get("domain_field", field)
    ctype = conv["type"]
    generator = _FROM_MODEL_GENERATORS.get(ctype)
    if generator is None:
        raise ValueError(f"Unknown converter type: {ctype} for field {field}")
    return generator(field, domain_field, conv)


def _to_active_enum(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(e.{domain_field}.to_string()),"


def _to_active_enum_opt(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(Some(e.{domain_field}.to_string())),"


def _to_active_bool(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(i64::from(e.{domain_field})),"


def _to_active_bool_opt(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(Some(i64::from(e.{domain_field}))),"


def _to_active_opt_bool(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(e.{domain_field}.map(i64::from)),"


def _to_active_int_cast(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(i64::from(e.{domain_field})),"


def _to_active_opt_int_cast(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(e.{domain_field}.map(i64::from)),"


def _to_active_json_serialize(
    field: str, domain_field: str, fallback: str,
) -> str:
    return (
        f"            {field}: ActiveValue::Set(Some(\n"
        f"                serde_json::to_string(&e.{domain_field})"
        f'.unwrap_or_else(|_| "{fallback}".into()),\n'
        f"            )),"
    )


def _to_active_json_array(field: str, domain_field: str) -> str:
    return _to_active_json_serialize(field, domain_field, "[]")


def _to_active_json_object(field: str, domain_field: str) -> str:
    return _to_active_json_serialize(field, domain_field, "{}")


def _to_active_json_array_required(field: str, domain_field: str) -> str:
    return (
        f"            {field}: ActiveValue::Set(\n"
        f"                serde_json::to_string(&e.{domain_field})"
        f'.unwrap_or_else(|_| "[]".into()),\n'
        f"            ),"
    )


def _to_active_json_object_opt(field: str, domain_field: str) -> str:
    return (
        f"            {field}: ActiveValue::Set(\n"
        f"                e.{domain_field}\n"
        f"                    .as_ref()\n"
        f"                    .and_then(|oc| serde_json::to_string(oc).ok()),\n"
        f"            ),"
    )


def _to_active_json_value(field: str, domain_field: str) -> str:
    return (
        f"            {field}: ActiveValue::Set(\n"
        f"                serde_json::to_string(&e.{domain_field}).unwrap_or_default(),\n"
        f"            ),"
    )


def _to_active_unwrap_default(field: str, domain_field: str) -> str:
    return f"            {field}: ActiveValue::Set(Some(e.{domain_field})),"


def _to_active_computed(field: str, domain_field: str) -> str | None:
    del field, domain_field
    return None


_TO_ACTIVE_GENERATORS: dict[str, Callable[[str, str], str | None]] = {
    "enum": _to_active_enum,
    "enum_opt": _to_active_enum_opt,
    "bool": _to_active_bool,
    "bool_opt": _to_active_bool_opt,
    "opt_bool": _to_active_opt_bool,
    "int_cast": _to_active_int_cast,
    "opt_int_cast": _to_active_opt_int_cast,
    "json_array": _to_active_json_array,
    "json_array_required": _to_active_json_array_required,
    "json_object": _to_active_json_object,
    "json_object_opt": _to_active_json_object_opt,
    "json_value": _to_active_json_value,
    "unwrap_default": _to_active_unwrap_default,
    "computed": _to_active_computed,
}


def gen_to_active_field(field: str, convert: dict[str, ConverterConfig]) -> str | None:
    conv = convert.get(field)
    if not conv:
        return f"            {field}: ActiveValue::Set(e.{field}),"

    domain_field = conv.get("domain_field", field)
    ctype = conv["type"]
    generator = _TO_ACTIVE_GENERATORS.get(ctype)
    if generator is None:
        raise ValueError(f"Unknown converter type: {ctype} for field {field}")
    return generator(field, domain_field)


def needs_serde_json(convert: dict[str, ConverterConfig]) -> bool:
    serde_types = {
        "json_array",
        "json_array_required",
        "json_object",
        "json_object_opt",
        "json_value",
    }
    return any(c["type"] in serde_types for c in convert.values())


def gen_test_block(name: str, entity: EntityConfig) -> str:
    """Generate #[cfg(test)] mod tests block for round-trip conversion test.

    Returns:
        The resulting ``str``.
    """
    domain_type = entity["domain"]
    entity_module = entity["entity"]
    fields = entity.get("fields", [])
    convert = entity.get("convert", {})
    not_set = entity.get("not_set", [])

    # Parse the actual entity Model struct to get field names and types
    model_fields = parse_entity_model_fields(entity_module)
    if not model_fields:
        return ""

    # Determine which fields are computed (not in Model)
    computed_fields = {f for f, c in convert.items() if c.get("type") == "computed"}

    # Build the sample Model constructor
    sample_lines = []
    for field_name, db_type in model_fields.items():
        if field_name in computed_fields:
            continue
        val = _test_value_for_field(field_name, db_type, name, convert, not_set)
        sample_lines.append(f"            {field_name}: {val},")

    # Determine the assertion field (first field in `fields` list)
    assert_field = fields[0] if fields else next(iter(model_fields.keys()))

    lines = [
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        f"    fn sample_{name}() -> {entity_module}::Model {{",
        f"        {entity_module}::Model {{",
    ]
    lines.extend(sample_lines)
    lines.extend([
        "        }",
        "    }",
        "",
        "    #[test]",
        f"    fn round_trip_{name}() {{",
        f"        let model = sample_{name}();",
        f"        let model_val = model.{assert_field}.clone();",
        "",
        "        // Model \u2192 Domain",
        f"        let domain: {domain_type} = model.into();",
        f"        assert_eq!(domain.{assert_field}, model_val);",
        "",
        "        // Domain \u2192 ActiveModel (should not panic)",
        f"        let _active: {entity_module}::ActiveModel = domain.into();",
        "    }",
        "}",
    ])

    return "\n".join(lines)


def all_fields_ordered(entity: EntityConfig) -> list[str]:
    """Return fields in safe evaluation order (computed fields first)."""
    fields = list(entity.get("fields", []))
    convert = entity.get("convert", {})
    # Computed fields reference other model fields by borrow (e.g. format!),
    # so they MUST be evaluated before direct fields that move those values.
    computed = [
        cf
        for cf in convert
        if cf not in fields and convert[cf].get("type") == "computed"
    ]
    extra = [
        cf
        for cf in convert
        if cf not in fields and convert[cf].get("type") != "computed"
    ]
    return computed + fields + extra


def gen_conversion_file(name: str, entity: EntityConfig) -> str:
    domain_type = entity["domain"]
    entity_module = entity["entity"]
    main_import = entity["import"]
    extra_imports = entity.get("extra_imports", [])
    entity.get("fields", [])
    not_set = entity.get("not_set", [])
    convert = entity.get("convert", {})

    lines = [GENERATED_HEADER, ""]
    lines.extend((
        "use sea_orm::ActiveValue;",
        "",
        f"use crate::database::seaorm::entities::{entity_module};",
        f"use {main_import};",
    ))
    lines.extend(f"use {imp};" for imp in extra_imports)

    from_model_fields = [
        gen_from_model_field(f, convert) for f in all_fields_ordered(entity)
    ]

    lines.extend((
        "",
        f"impl From<{entity_module}::Model> for {domain_type} {{",
        f"    fn from(m: {entity_module}::Model) -> Self {{",
        "        Self {",
    ))
    for fline in from_model_fields:
        lines.append(fline)
    lines.extend(("        }", "    }", "}"))

    to_active_fields = []
    for f in all_fields_ordered(entity):
        result = gen_to_active_field(f, convert)
        if result is not None:
            to_active_fields.append(result)
    to_active_fields.extend(
        f"            {ns_field}: ActiveValue::NotSet," for ns_field in not_set
    )

    lines.extend((
        "",
        f"impl From<{domain_type}> for {entity_module}::ActiveModel {{",
        f"    fn from(e: {domain_type}) -> Self {{",
        "        Self {",
    ))
    for fline in to_active_fields:
        lines.append(fline)
    lines.extend(("        }", "    }", "}"))

    test_block = gen_test_block(name, entity)
    if test_block:
        lines.append(test_block)

    return "\n".join(lines) + "\n"


def gen_mod_rs(names: list[str]) -> str:
    lines = [GENERATED_HEADER, ""]
    lines.extend(f"pub mod {n};" for n in sorted(names))
    return "\n".join(lines) + "\n"


def main() -> None:
    with Path(CONFIG_PATH).open("rb") as f:
        config = t.TypeAdapter(dict[str, EntityConfig]).validate_python(
            tomllib.load(f), experimental_allow_partial=True,
        )

    entity_names = []

    for name, entity in config.items():
        entity_names.append(name)
        content = gen_conversion_file(name, entity)
        out_path = OUTPUT_DIR / f"{name}.rs"
        out_path.write_text(content)
        print(f"  ✓ {name}.rs ({len(content)} bytes)")

    mod_content = gen_mod_rs(entity_names)
    (OUTPUT_DIR / "mod.rs").write_text(mod_content)
    print(f"  ✓ mod.rs ({len(entity_names)} modules)")
    print(f"Generated {len(entity_names)} conversion files")


if __name__ == "__main__":
    main()
