digraph {
  node [shape=plaintext]
  subgraph {
    _1 [label="ADR 001: Modular Crates Architecture"; URL="001-modular-crates-architecture.html"];
    _2 [label="ADR 002: Async-First Architecture"; URL="002-async-first-architecture.html"];
    _3 [label="ADR 003: Unified Provider Architecture & Routing"; URL="003-unified-provider-architecture.html"];
    _4 [label="ADR 004: Event Bus (Local and Distributed)"; URL="004-event-bus-local-distributed.html"];
    _5 [label="ADR 005: Context Cache Support (Moka and Redis)"; URL="005-context-cache-support.html"];
    _6 [label="ADR 006: Code Audit and Architecture Improvements"; URL="006-code-audit-and-improvements.html"];
    _7 [label="ADR 007: Integrated Web Administration Interface"; URL="007-integrated-web-administration-interface.html"];
    _8 [label="ADR 008: Git-Aware Semantic Indexing v0.2.0"; URL="008-git-aware-semantic-indexing-v0.2.0.html"];
    _9 [label="ADR 009: Persistent Session Memory v0.2.0"; URL="009-persistent-session-memory-v0.2.0.html"];
    _10 [label="ADR 010: Hooks Subsystem with Agent-Backed Processing"; URL="010-hooks-subsystem-agent-backed.html"];
    _11 [label="ADR 011: HTTP Transport - Request-Response Pattern Over SSE Streaming"; URL="011-http-transport-request-response-pattern.html"];
    _12 [label="ADR 012: Two-Layer Dependency Injection Strategy"; URL="012-di-strategy-two-layer-approach.html"];
    _13 [label="ADR 013: Clean Architecture Crate Separation"; URL="013-clean-architecture-crate-separation.html"];
    _14 [label="ADR 014: Multi-Domain Architecture Strategy"; URL="014-multi-domain-architecture.html"];
    _15 [label="ADR 015: Workspace Structure for Shared Libraries"; URL="015-workspace-shared-libraries.html"];
    _16 [label="ADR 016: Integration Points and Adapter Pattern"; URL="016-integration-points-adapter-pattern.html"];
    _17 [label="ADR 017: Phased Feature Integration Roadmap"; URL="017-phased-feature-integration.html"];
    _18 [label="ADR 018: Hybrid Caching Strategy"; URL="018-hybrid-caching-strategy.html"];
    _19 [label="ADR 019: Error Handling Strategy"; URL="019-error-handling-strategy.html"];
    _20 [label="ADR 020: Testing Strategy for Integrated Code"; URL="020-testing-strategy-integration.html"];
    _21 [label="ADR 021: Dependency Management Strategy"; URL="021-dependency-management.html"];
    _22 [label="ADR 022: Continuous Integration Strategy"; URL="022-ci-integration-strategy.html"];
    _23 [label="ADR 023: Inventory to Linkme Migration"; URL="023-inventory-to-linkme-migration.html"];
    _24 [label="ADR 024: Shaku to dill DI Migration"; URL="024-simplified-dependency-injection.html"];
    _25 [label="ADR 025: Figment Configuration Migration"; URL="025-figment-configuration.html"];
    _26 [label="ADR 026: API Routing Refactor (Rocket vs Poem)"; URL="026-routing-refactor-rocket-poem.html"];
    _27 [label="ADR 027: Architecture Evolution v0.1.3 - Onion/Clean Enhancement"; URL="027-architecture-evolution-v013.html"];
    _28 [label="ADR 028: Advanced Code Browser UI v0.2.0"; URL="028-advanced-code-browser-v020.html"];
    _29 [label="ADR 029: Hexagonal Architecture with dill IoC"; URL="029-hexagonal-architecture-dill.html"];
    _30 [label="ADR 030: Multi-Provider Strategy"; URL="030-multi-provider-strategy.html"];
    _31 [label="ADR 031: Documentation Excellence"; URL="031-documentation-excellence.html"];
    _32 [label="ADR 032: Agent & Quality Domain Extension (MCB-Only)"; URL="032-agent-quality-domain-extension.html"];
    _33 [label="ADR 033: MCP Handler Consolidation"; URL="033-mcp-handler-consolidation.html"];
    _34 [label="ADR 034: Workflow Core — Finite State Machine and Persistence"; URL="034-workflow-core-fsm.html"];
    _35 [label="ADR 035: Context Scout — Project State Discovery"; URL="035-context-scout.html"];
    _36 [label="ADR 036: Enforcement Layer — Policies and Guards"; URL="036-enforcement-policies.html"];
    _37 [label="ADR 037: Workflow Orchestrator — Coordination and MCP Integration"; URL="037-workflow-orchestrator.html"];
    _38 [label="ADR 038: Multi-Tier Execution Model — Integration of ADR-034–037"; URL="038-multi-tier-execution-model.html"];
    _39 [label="ADR 039: (missing/reserved)"; fontcolor="gray50"];
    _40 [label="ADR 040: (missing/reserved)"; fontcolor="gray50"];
    _41 [label="ADR 041: Integrated Context System Architecture v0.4.0"; URL="041-integrated-context-system-architecture.html"];
    _42 [label="ADR 042: Knowledge Graph for Code Context and Relationships"; URL="042-knowledge-graph-code-context.html"];
    _43 [label="ADR 043: Hybrid Search & Discovery for Context"; URL="043-hybrid-search-discovery.html"];
    _44 [label="ADR 044: Lightweight Discovery Models for Context Routing"; URL="044-lightweight-discovery-models.html"];
    _45 [label="ADR 045: Context Versioning & Freshness Tracking"; URL="045-context-versioning-freshness.html"];
    _46 [label="ADR 046: Integration with ADR-034-037 & Policies"; URL="046-integration-adr-034-037-policies.html"];
    _47 [label="ADR 047: Project Architecture - Central Hub and Multi-Dimensional Coordination"; URL="047-project-architecture.html"];
    _1 -> _2 [style="dotted", weight=1];
    _2 -> _3 [style="dotted", weight=1];
    _3 -> _4 [style="dotted", weight=1];
    _4 -> _5 [style="dotted", weight=1];
    _5 -> _6 [style="dotted", weight=1];
    _6 -> _7 [style="dotted", weight=1];
    _7 -> _8 [style="dotted", weight=1];
    _8 -> _9 [style="dotted", weight=1];
    _9 -> _10 [style="dotted", weight=1];
    _10 -> _11 [style="dotted", weight=1];
    _11 -> _12 [style="dotted", weight=1];
    _12 -> _13 [style="dotted", weight=1];
    _13 -> _14 [style="dotted", weight=1];
    _14 -> _15 [style="dotted", weight=1];
    _15 -> _16 [style="dotted", weight=1];
    _16 -> _17 [style="dotted", weight=1];
    _17 -> _18 [style="dotted", weight=1];
    _18 -> _19 [style="dotted", weight=1];
    _19 -> _20 [style="dotted", weight=1];
    _20 -> _21 [style="dotted", weight=1];
    _21 -> _22 [style="dotted", weight=1];
    _22 -> _23 [style="dotted", weight=1];
    _23 -> _24 [style="dotted", weight=1];
    _24 -> _25 [style="dotted", weight=1];
    _25 -> _26 [style="dotted", weight=1];
    _26 -> _27 [style="dotted", weight=1];
    _27 -> _28 [style="dotted", weight=1];
    _28 -> _29 [style="dotted", weight=1];
    _29 -> _30 [style="dotted", weight=1];
    _30 -> _31 [style="dotted", weight=1];
    _31 -> _32 [style="dotted", weight=1];
    _32 -> _33 [style="dotted", weight=1];
    _33 -> _34 [style="dotted", weight=1];
    _34 -> _35 [style="dotted", weight=1];
    _35 -> _36 [style="dotted", weight=1];
    _36 -> _37 [style="dotted", weight=1];
    _37 -> _38 [style="dotted", weight=1];
    _38 -> _39 [style="dotted", weight=1];
    _39 -> _40 [style="dotted", weight=1];
    _40 -> _41 [style="dotted", weight=1];
    _41 -> _42 [style="dotted", weight=1];
    _42 -> _43 [style="dotted", weight=1];
    _43 -> _44 [style="dotted", weight=1];
    _44 -> _45 [style="dotted", weight=1];
    _45 -> _46 [style="dotted", weight=1];
    _46 -> _47 [style="dotted", weight=1];
  }
}
