# syntax=docker/dockerfile:1
# Generated by `flext_infra codegen conform` for mcb_scripts.
# === SECTION: header (managed) ===
# Source: template (base/tests/fixtures/ci/docker/debian.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Debian.
FROM debian:bookworm-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === SECTION: base packages (managed) ===
# Source: template (distro-specific seed contract)
# The seed is the whole host contract: curl fetches mise, git is what uv shells
# out to for the flext-infra git+https requirement, make invokes the verbs.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash ca-certificates curl git make \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --shell /bin/bash runner
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: generated bin/mise + .mise.toml
# The canonical make setup verb below owns the committed Mise bootstrap
# and the frozen installation of every tool the committed mise.lock pins, as
# the same unprivileged runtime user.
# The setup RUN receives GitHub's credential only through a BuildKit secret.
# Never persist build credentials in ARG, ENV, layers, or image configuration.
ARG RUNNER_USER=runner
ENV HOME=/home/${RUNNER_USER}
ENV XDG_DATA_HOME=${HOME}/.local/share \
    XDG_CACHE_HOME=${HOME}/.cache \
    XDG_STATE_HOME=${HOME}/.local/state \
    MISE_DATA_DIR=${HOME}/.local/share/mise
WORKDIR /workspace
RUN --mount=type=bind,source=.,target=/source,ro \
    cp -R /source/. /workspace/ \
    && chown -R runner:runner /workspace
USER runner
ENV PATH="$MISE_DATA_DIR/shims:${PATH}"
# End SECTION: managed tool bootstrap

# === SECTION: bootstrap proof (managed) ===
# Source: template (clean-machine bootstrap through the canonical verb)
# The image exists to PROVE that a clean machine can bootstrap this project
# with nothing but the declared toolchain. It therefore runs the canonical
# setup verb fail-closed: any non-zero status fails the build. An earlier
# revision wrapped this in `set +e` and soft-passed whenever the output
# mentioned uv.lock/flext-core, which turned the proof into a bypass -- a
# broken bootstrap still produced a green image.
ENV CI=Y
RUN --mount=type=secret,id=github_token,env=GITHUB_TOKEN,required=true \
    make setup
# End SECTION: bootstrap proof

ENTRYPOINT []
CMD ["make", "help"]
