# Generated by `flext_infra codegen conform` for mcb_scripts.
# === SECTION: header (managed) ===
# Source: template (base/tests/fixtures/ci/docker/fedora.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Fedora.
FROM fedora:41

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === SECTION: base packages (managed) ===
# Source: template (distro-specific seed contract)
# The seed is the whole host contract: curl fetches mise, git is what uv shells
# out to for the flext-infra git+https requirement, make invokes the verbs.
# libicu-devel is pulled in because tokei (cargo-backed) needs a Rust toolchain,
# which in turn needs it — init-setup.sh provisions Rust via mise, so the native
# ICU headers must be present at the system layer.
RUN dnf install -y \
      bash ca-certificates curl git make libicu-devel \
    && dnf clean all
# End SECTION: base packages

WORKDIR /workspace
# init-setup.sh is the single declarative bootstrap: it downloads one throwaway
# mise, projects the managed registry from the typed SSOT (config/tools.yaml),
# installs everything mise manages (mise, uv, go, node, gh, docker...) including
# itself, then hands control to the managed copy and deletes the throwaway.
# The GITHUB_TOKEN build-arg authenticates GitHub API reads during provisioning.
ARG GITHUB_TOKEN
ENV MISE_GITHUB_TOKEN=${GITHUB_TOKEN}
COPY . .

# === SECTION: managed tool bootstrap (managed) ===
# Source: template (init-setup.sh, the project's own bootstrap entrypoint)
# Everything else — mise, uv, go, node, bun, gh, docker, kubectl, helm, tmux —
# is provisioned by init-setup.sh through mise. The previous revision
# curl-installed mise, uv, rustup and a hardcoded Go 1.23.4 here, which meant
# the "clean machine proof" was really proving a hand-assembled toolchain that
# no operator would reproduce. Pinning Go in a Dockerfile also silently
# overrode the version the project declares.
RUN sh ./init-setup.sh
ENV PATH="/root/.local/share/mise/shims:${PATH}"
# End SECTION: managed tool bootstrap

# === SECTION: bootstrap proof (managed) ===
# Source: template (clean-machine bootstrap through the canonical verb)
# The image exists to PROVE that a clean machine can bootstrap this project
# with nothing but the declared toolchain. It therefore runs the canonical
# setup verb fail-closed: any non-zero status fails the build. An earlier
# revision wrapped this in `set +e` and soft-passed whenever the output
# mentioned uv.lock/flext-core, which turned the proof into a bypass -- a
# broken bootstrap still produced a green image.
ENV CI=Y
RUN make setup
# End SECTION: bootstrap proof

ENTRYPOINT []
CMD ["make", "help"]
