# Generated by `flext_infra codegen conform` for mcb_scripts.
# === SECTION: header (managed) ===
# Source: template (base/tests/fixtures/ci/docker/ubuntu.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Ubuntu.
FROM ubuntu:24.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === SECTION: base packages (managed) ===
# Source: template (distro-specific package list)
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash ca-certificates curl git make build-essential libicu-dev \
    && rm -rf /var/lib/apt/lists/*
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: config:python_version, template (installer URLs)
# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | sh
# uv is intentionally supplied by the caller environment; install it explicitly
# in clean-machine images so the project bootstrap can resolve dependencies.
RUN curl -fsSL https://astral.sh/uv/install.sh | sh
# tokei (and any future cargo-backed mise tool) needs a Rust toolchain.
RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
# go is required for mise-managed beads (go:github.com/steveyegge/beads/cmd/bd).
RUN curl -fsSL https://go.dev/dl/go1.23.4.linux-amd64.tar.gz | tar -C /usr/local -xzf - \
    && ln -sf /usr/local/go/bin/go /usr/local/bin/go
ENV PATH="/usr/local/go/bin:/root/.local/bin:/root/.cargo/bin:/root/.local/share/mise/shims:${PATH}"
# End SECTION: managed tool bootstrap

WORKDIR /workspace
COPY . .

# === SECTION: mise install (managed) ===
# Source: computed (reads .mise.toml from copied workspace)
RUN mise trust .mise.toml && mise install --yes
# End SECTION: mise install

# === SECTION: bootstrap proof (managed) ===
# Source: template (clean-machine bootstrap through the canonical verb)
# The image exists to PROVE that a clean machine can bootstrap this project
# with nothing but the declared toolchain. It therefore runs the canonical
# setup verb fail-closed: any non-zero status fails the build. An earlier
# revision wrapped this in `set +e` and soft-passed whenever the output
# mentioned uv.lock/flext-core, which turned the proof into a bypass -- a
# broken bootstrap still produced a green image.
ENV CI=Y
RUN make setup
# End SECTION: bootstrap proof

ENTRYPOINT []
CMD ["make", "help"]
