//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub worktree_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub session_summary_id: String,
    #[sea_orm(column_type = "Text")]
    pub agent_type: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_session_id: Option<String>,
    pub started_at: i64,
    pub ended_at: Option<i64>,
    pub duration_ms: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt_summary: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_summary: Option<String>,
    pub token_count: Option<i64>,
    pub tool_calls_count: Option<i64>,
    pub delegations_count: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
