//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "project_issues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub org_id: String,
    #[sea_orm(column_type = "Text")]
    pub project_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub phase_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub issue_type: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub priority: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub assignee: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub labels: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub closed_at: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    pub estimated_minutes: Option<i64>,
    pub actual_minutes: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    #[sea_orm(column_type = "Text")]
    pub design: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_issue_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub closed_reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
