//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "session_summaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub org_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub project_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub repo_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub session_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub topics: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub decisions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub next_steps: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub key_files: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub origin_context: Option<String>,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
